# Wizualizacja danych genomicznych

## Wprowadzenie

W tym notatniku przeprowadzimy analizę i wizualizację cech sekwencji DNA, takich jak zawartość GC i asymetria GC, wykorzystując technikę przesuwnych okien. Następnie dane zwizualizujemy przy pomocy [Circos](http://circos.ca/) - popularnego narzędzia umożliwiającego kolistą reprezentację danych genomicznych. Pakiet Circos jest niezwykle elastyczny i doskonale udokumentowany, [z wieloma przykładami i dokładnymi opisami funkcjonalności.](http://circos.ca/documentation/) 
![http://circos.ca/intro/genomic_data/](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-021-00922-y/MediaObjects/41588_2021_922_Fig1_HTML.png)
*https://doi.org/10.1038/s41588-021-00922-y*

## Import Bibliotek

Przed rozpoczęciem analizy danych i wizualizacji importujemy kilka kluczowych bibliotek:
1. sys: Umożliwia interakcję z interpreterem Pythona i zarządzanie argumentami wiersza poleceń.
2. pandas (pd): Służy do łatwego wczytywania i przetwarzania danych w formie tabelarycznej.
3. numpy (np): Zawiera narzędzia do obliczeń numerycznych i operacji na danych wielowymiarowych.
4. plotnine: Umożliwia tworzenie wykresów i wizualizację danych, oparta jest na gramatyce pakietu ggplot2 z języka R.

In [1]:
import sys
import pandas as pd
import numpy as np
from plotnine import *

## Zdefiniowanie funkcji 

Zdefinujmy funkcje wykorzystywane podczas analizy

#### Odczytywanie Sekwencji DNA


Aby analizować sekwencje DNA, musimy najpierw załadować dane z pliku FASTA.

Funkcja *read_fasta* służy do wczytywania sekwencji DNA z pliku w formacie FASTA do słownika. 

**Parametry:**
*file_path:* Ścieżka do pliku FASTA z sekwencją DNA.


**Zwraca:**
*fadict:* Słownik, w którym kluczami są nazwy sekwencji, a wartościami są odpowiadające im sekwencje DNA.

In [2]:
def read_fasta(file_path):
    fadict = {}
    with open(file_path) as file:
        idx = ""
        for line in file:
            if line.startswith(">"):
                idx = line.strip().split()[0][1:]
                fadict[idx] = ""
            else:
                fadict[idx] += line.strip()
    return fadict

#### Analiza w ruchomych oknach

Jedną z podstawowych technik analizy sekwencji jest analiza w ruchomych oknach (sliding windows). Polega ona na podziale sekwencji na małe, nakładające się segmenty (okna) i wykonywaniu obliczeń w każdym z nich.

Funkcja *sliding_window* wykonuje analizę ruchomych okien na sekwencji DNA.

**Parametry:**
*seq:* Analizowana sekwencja DNA.
*size:* Rozmiar okna.
*step:* Krok przesuwania okna.
*func:* Funkcja, która ma zostać zastosowana do każdego okna.

**Zwraca:**
Lista wyników analizy okien, gdzie każdy wynik zawiera informacje o początku i końcu okna oraz wynik funkcji *func* na tym oknie.

In [3]:
def sliding_window(seq, size, step, func):
    results = []
    for start in range(0, len(seq) - size + 1, step):
        subseq = seq[start:start + size]
        results.append([start, start + size, func(subseq)])
    return results

#### Obliczanie Zawartości GC

**Wprowadzenie:**
Zawartość GC to miara proporcji zasad guaniny (G) i cytozyny (C) w sekwencji DNA. 

Funkcja *gc_content* Oblicza zawartość GC w danej sekwencji DNA.

**Parametry:**
*seq:* Analizowana sekwencja DNA.

**Zwraca:**
Procentowy udział GC w sekwencji.

In [4]:

def gc_content(seq):
    gc_count = sum(1 for base in seq if base.lower() in ["g", "c"])
    return gc_count / len(seq)

#### Obliczanie Skosu GC

Asymetria GC (GC skew) określa różnicę w zawartości guaniny i cytozyny na jednej nici DNA. 

Funkcja *gc_skew* oblicza asymetrię GC w danej sekwencji DNA.
**Parametry:**

*seq:* Analizowana sekwencja DNA.

**Zwraca:**
Asymetrię GC w sekwencji.

In [5]:
def gc_skew(seq):
    g = seq.lower().count("g")
    c = seq.lower().count("c")
    return (g - c) / (g + c) if (g + c) > 0 else 0

#### Skalowanie Min-Max

W niektórych przypadkach ważne jest przeskalowanie naszych danych tak, aby mieściły się w określonym zakresie, na przykład [0, 1].

Funkcja *rescale_range* wykonuje przeskalowanie wartości x z zakresu [min_x, max_x] na inny zakres [i, j].

**Parametry:**
*x:* Wartość do przeskalowania.
*min_x:* Dolny zakres oryginalnych wartości.
*max_x:* Górny zakres oryginalnych wartości.
*i:* Dolny zakres przeskalowanych wartości.
*j:* Górny zakres przeskalowanych wartości.

**Zwraca:**
Przeskalowaną wartość *x* w nowym zakresie [i, j].

In [6]:
def rescale_range(x, min_x, max_x, i=0, j=1):
    return(i+((x-min_x)*(j-i)/(max_x-min_x)))

#### Analiza Częstości K-merów

K-mery to sekwencje o długości k w sekwencji DNA. Analiza częstości k-merów może dostarczyć wglądu w charakterystykę sekwencji. 

Funkcja *kmer_freq* analizuje sekwencję DNA w poszukiwaniu wystąpień k-merów i zlicza ich częstość.

**Parametry:**
*seq:* Analizowana sekwencja DNA.
*k:* Długość k-mera (domyślnie 20).

**Zwraca:**
Słownik, w którym kluczami są k-mery, a wartościami liczba ich wystąpień w sekwencji.

In [7]:
def kmer_freq(seq, k=20):
    kmer_dic = {}
    for i in range(len(seq) - k + 1):
        subseq = seq[i:i + k]
        kmer_dic[subseq] = kmer_dic.get(subseq, 0) + 1
    return kmer_dic

#### Pobieranie Pozycji K-merów

Funkcja *kmer_pos* znajduje pozycje wystąpień danego k-mera w sekwencji DNA.

**Parametry:**
*seq:* Analizowana sekwencja DNA.
*kmer:* K-mer, którego pozycje chcemy znaleźć.

**Zwraca:**
Lista pozycji wystąpień k-mera, gdzie każda pozycja to krotka (start, stop).

In [8]:
def kmer_pos(seq, kmer):
    pos = []
    k = len(kmer)
    start = 0
    while True:
        start = seq.find(kmer, start)
        if start == -1:
            break
        pos.append((start, start + k))
        start += 1
    return pos

#### Scalanie Nachodzących Zakresów 

Funkcja merge_overlaps łączy nakładające się zakresy (pary start-stop) w sekwencjach. Funkcja wymaga posortowanych zakresów wejściowych. 

**Parametry:**
*ranges:* Lista zakresów do połączenia.

**Zwraca:**
Złączone zakresy, które eliminują nakładające się fragmenty i tworzą spójne obszary.

In [9]:
def merge_overlaps(ranges):
    if not ranges:
        return []
    
    ranges = sorted(ranges)
    merged = [ranges[0]]
    
    for current in ranges[1:]:
        last = merged[-1]
        if current[0] <= last[1]:  # Overlapping intervals
            merged[-1] = [last[0], max(last[1], current[1])]
        else:
            merged.append(current)
    return merged

## Przygotowanie genomu Wejściowego

W tej sekcji przygotujemy dane genomu do analizy. Pobierzemy i rozpakujemy plik FASTA z sekwencją genomu i zmienimy jego nazwę na bardziej intuicyjną. Proszę zmienić genom na wybrany przez siebie kompletny genom bakteryjny, opublikowany nie wcześniej niż w 2018 roku. Genom można pobrać z bazy danych [NCBI Genomes](https://www.ncbi.nlm.nih.gov/datasets/genomes/).

In [10]:
!wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/027/325/GCF_000027325.1_ASM2732v1/GCF_000027325.1_ASM2732v1_genomic.fna.gz

--2025-10-28 13:14:08--  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/027/325/GCF_000027325.1_ASM2732v1/GCF_000027325.1_ASM2732v1_genomic.fna.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.11, 130.14.250.12, 130.14.250.7, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 165775 (162K) [application/x-gzip]
Saving to: ‘GCF_000027325.1_ASM2732v1_genomic.fna.gz’

GCF_000027325.1_ASM 100%[===================>] 161.89K   522KB/s    in 0.3s

2025-10-28 13:14:09 (522 KB/s) - ‘GCF_000027325.1_ASM2732v1_genomic.fna.gz’ saved [165775/165775]

In [11]:
!gunzip GCF_000027325.1_ASM2732v1_genomic.fna.gz

In [12]:
!mv GCF_000027325.1_ASM2732v1_genomic.fna mycoplasma.fa

In [10]:
in_fasta = "GENOME_thin.fasta"
fadict = read_fasta(in_fasta)

Analizę przeprowadzimy jedynie dla chromosomu bakteryjnego, więc jeżeli w złożeniu znajdują się jakiekolwiek dodatkowe sekwencje (np. plazmidy) proszę je zignorować, i do dalszych kroków wykorzystać jedynie sekwencję największej cząsteczki.

In [11]:
fadict.keys()

dict_keys(['ptg000007l', 'ptg000003l', 'ptg000012l', 'ptg000008l', 'ptg000002l', 'ptg000016l', 'ptg000018l', 'ptg000014l', 'ptg000011l', 'ptg000015l', 'ptg000010l', 'ptg000004l', 'ptg000001l', 'ptg000009l', 'ptg000013l', 'ptg000017l'])

In [12]:
for key in fadict.keys():
    print(key, len(fadict[key]))

ptg000007l 4962671
ptg000003l 1805757
ptg000012l 2044213
ptg000008l 2324804
ptg000002l 2259285
ptg000016l 2349775
ptg000018l 2524214
ptg000014l 2808376
ptg000011l 3109985
ptg000015l 3330951
ptg000010l 4100071
ptg000004l 3736295
ptg000001l 3711849
ptg000009l 4221094
ptg000013l 4262825
ptg000017l 4416379

In [16]:
chromnames = list(fadict.keys())
chromnames

['ptg000007l',
 'ptg000003l',
 'ptg000012l',
 'ptg000008l',
 'ptg000002l',
 'ptg000016l',
 'ptg000018l',
 'ptg000014l',
 'ptg000011l',
 'ptg000015l',
 'ptg000010l',
 'ptg000004l',
 'ptg000001l',
 'ptg000009l',
 'ptg000013l',
 'ptg000017l']

In [18]:
for chromname in chromnames:
    seq = fadict[chromname]
    seq_length = len(seq)
    print(seq_length)

4962671
1805757
2044213
2324804
2259285
2349775
2524214
2808376
3109985
3330951
4100071
3736295
3711849
4221094
4262825
4416379

### Analiza Zawartości GC z Wykorzystaniem Okien


W tej sekcji wykorzystamy funkcję *sliding_window*, aby obliczyć zawartość GC w sekwencji genomu korzystając z okien o zdefiniowanej wielkości i kroku. Poeksperymentuj z wielkością okna oraz kroku, aby zobaczyć jak parametry te wpływają na wynik. Poniważ Circos wymaga, aby zakresy danych nie nakładały się, w ostatnim przebiegu ustaw długość kroku równą wielkości okna.

In [20]:
w_size = 50000
w_step = 50000

In [53]:
from copy import deepcopy
gcdf_dict = {}

for chromname in chromnames:
    seq = fadict[chromname]
    seq_length = len(seq)
    print(seq_length)
    
    gc = sliding_window(seq, w_size, w_step, gc_content)

    gcdf = pd.DataFrame(gc, columns=["start", "stop", "gc"])
    print(gcdf)
    gcdf_dict[chromname]= gcdf

print(len(gcdf_dict))

4962671
      start     stop       gc
0         0    50000  0.47702
1     50000   100000  0.49118
2    100000   150000  0.47806
3    150000   200000  0.46692
4    200000   250000  0.45054
..      ...      ...      ...
94  4700000  4750000  0.51006
95  4750000  4800000  0.44950
96  4800000  4850000  0.50556
97  4850000  4900000  0.48292
98  4900000  4950000  0.45106

[99 rows x 3 columns]
1805757
      start     stop       gc
0         0    50000  0.51252
1     50000   100000  0.48708
2    100000   150000  0.45720
3    150000   200000  0.47562
4    200000   250000  0.48344
5    250000   300000  0.48452
6    300000   350000  0.49106
7    350000   400000  0.49168
8    400000   450000  0.47088
9    450000   500000  0.47148
10   500000   550000  0.50730
11   550000   600000  0.49122
12   600000   650000  0.50270
13   650000   700000  0.49546
14   700000   750000  0.50182
15   750000   800000  0.49460
16   800000   850000  0.42122
17   850000   900000  0.42900
18   900000   950000  0.49362
19   950000  1000000  0.48532
20  1000000  1050000  0.44674
21  1050000  1100000  0.47220
22  1100000  1150000  0.47860
23  1150000  1200000  0.49196
24  1200000  1250000  0.49112
25  1250000  1300000  0.48626
26  1300000  1350000  0.49164
27  1350000  1400000  0.48070
28  1400000  1450000  0.45520
29  1450000  1500000  0.47410
30  1500000  1550000  0.47270
31  1550000  1600000  0.44628
32  1600000  1650000  0.46284
33  1650000  1700000  0.47868
34  1700000  1750000  0.47410
35  1750000  1800000  0.47882
2044213
      start     stop       gc
0         0    50000  0.48868
1     50000   100000  0.47428
2    100000   150000  0.46782
3    150000   200000  0.47744
4    200000   250000  0.49376
5    250000   300000  0.49670
6    300000   350000  0.48990
7    350000   400000  0.49128
8    400000   450000  0.50420
9    450000   500000  0.49456
10   500000   550000  0.48360
11   550000   600000  0.48510
12   600000   650000  0.49054
13   650000   700000  0.48908
14   700000   750000  0.48864
15   750000   800000  0.48872
16   800000   850000  0.50524
17   850000   900000  0.50698
18   900000   950000  0.46854
19   950000  1000000  0.48774
20  1000000  1050000  0.49218
21  1050000  1100000  0.47674
22  1100000  1150000  0.46442
23  1150000  1200000  0.52660
24  1200000  1250000  0.49242
25  1250000  1300000  0.50372
26  1300000  1350000  0.51046
27  1350000  1400000  0.48354
28  1400000  1450000  0.49308
29  1450000  1500000  0.47970
30  1500000  1550000  0.48700
31  1550000  1600000  0.48988
32  1600000  1650000  0.46572
33  1650000  1700000  0.48220
34  1700000  1750000  0.48996
35  1750000  1800000  0.47514
36  1800000  1850000  0.47388
37  1850000  1900000  0.46650
38  1900000  1950000  0.49326
39  1950000  2000000  0.48294
2324804
      start     stop       gc
0         0    50000  0.48224
1     50000   100000  0.47114
2    100000   150000  0.46224
3    150000   200000  0.48166
4    200000   250000  0.48534
5    250000   300000  0.44964
6    300000   350000  0.45992
7    350000   400000  0.48562
8    400000   450000  0.48344
9    450000   500000  0.49658
10   500000   550000  0.49962
11   550000   600000  0.48510
12   600000   650000  0.49088
13   650000   700000  0.50954
14   700000   750000  0.49292
15   750000   800000  0.48828
16   800000   850000  0.48774
17   850000   900000  0.48474
18   900000   950000  0.48560
19   950000  1000000  0.45190
20  1000000  1050000  0.45404
21  1050000  1100000  0.50412
22  1100000  1150000  0.48658
23  1150000  1200000  0.50076
24  1200000  1250000  0.49878
25  1250000  1300000  0.49508
26  1300000  1350000  0.49032
27  1350000  1400000  0.49124
28  1400000  1450000  0.50006
29  1450000  1500000  0.47634
30  1500000  1550000  0.49002
31  1550000  1600000  0.48244
32  1600000  1650000  0.49342
33  1650000  1700000  0.47970
34  1700000  1750000  0.50004
35  1750000  1800000  0.49078
36  1800000  1850000  0.47426
37  1850000  1900000  0.49002
38  1900000  1950000  0.49180
39  1950000  2000000  0.49638
40  2000000  2050000  0.46454
41  2050000  2100000  0.44060
42  2100000  2150000  0.47500
43  2150000  2200000  0.46726
44  2200000  2250000  0.48052
45  2250000  2300000  0.45070
2259285
      start     stop       gc
0         0    50000  0.48306
1     50000   100000  0.47240
2    100000   150000  0.45258
3    150000   200000  0.46116
4    200000   250000  0.48144
5    250000   300000  0.47364
6    300000   350000  0.46788
7    350000   400000  0.48014
8    400000   450000  0.47846
9    450000   500000  0.48024
10   500000   550000  0.46442
11   550000   600000  0.48078
12   600000   650000  0.49028
13   650000   700000  0.46910
14   700000   750000  0.48408
15   750000   800000  0.48794
16   800000   850000  0.49096
17   850000   900000  0.42882
18   900000   950000  0.42902
19   950000  1000000  0.48146
20  1000000  1050000  0.49396
21  1050000  1100000  0.49620
22  1100000  1150000  0.50170
23  1150000  1200000  0.48336
24  1200000  1250000  0.49464
25  1250000  1300000  0.49766
26  1300000  1350000  0.50450
27  1350000  1400000  0.49260
28  1400000  1450000  0.47966
29  1450000  1500000  0.49366
30  1500000  1550000  0.48950
31  1550000  1600000  0.50732
32  1600000  1650000  0.48676
33  1650000  1700000  0.46544
34  1700000  1750000  0.49470
35  1750000  1800000  0.49734
36  1800000  1850000  0.48882
37  1850000  1900000  0.47222
38  1900000  1950000  0.47584
39  1950000  2000000  0.48928
40  2000000  2050000  0.48780
41  2050000  2100000  0.48834
42  2100000  2150000  0.49232
43  2150000  2200000  0.49502
44  2200000  2250000  0.48846
2349775
      start     stop       gc
0         0    50000  0.49180
1     50000   100000  0.42880
2    100000   150000  0.50326
3    150000   200000  0.48894
4    200000   250000  0.48590
5    250000   300000  0.49890
6    300000   350000  0.49284
7    350000   400000  0.49302
8    400000   450000  0.48322
9    450000   500000  0.50524
10   500000   550000  0.49554
11   550000   600000  0.48864
12   600000   650000  0.50380
13   650000   700000  0.49122
14   700000   750000  0.48922
15   750000   800000  0.49240
16   800000   850000  0.50226
17   850000   900000  0.50514
18   900000   950000  0.49770
19   950000  1000000  0.49360
20  1000000  1050000  0.49928
21  1050000  1100000  0.49890
22  1100000  1150000  0.49680
23  1150000  1200000  0.49648
24  1200000  1250000  0.46400
25  1250000  1300000  0.48156
26  1300000  1350000  0.49246
27  1350000  1400000  0.50388
28  1400000  1450000  0.48664
29  1450000  1500000  0.49078
30  1500000  1550000  0.49666
31  1550000  1600000  0.50022
32  1600000  1650000  0.48808
33  1650000  1700000  0.48260
34  1700000  1750000  0.50464
35  1750000  1800000  0.49584
36  1800000  1850000  0.47838
37  1850000  1900000  0.48966
38  1900000  1950000  0.48514
39  1950000  2000000  0.48726
40  2000000  2050000  0.48160
41  2050000  2100000  0.50218
42  2100000  2150000  0.47670
43  2150000  2200000  0.48432
44  2200000  2250000  0.48714
45  2250000  2300000  0.42568
2524214
      start     stop       gc
0         0    50000  0.46076
1     50000   100000  0.44424
2    100000   150000  0.46586
3    150000   200000  0.49480
4    200000   250000  0.48938
5    250000   300000  0.50382
6    300000   350000  0.49172
7    350000   400000  0.48780
8    400000   450000  0.48614
9    450000   500000  0.49616
10   500000   550000  0.48128
11   550000   600000  0.49710
12   600000   650000  0.50326
13   650000   700000  0.48994
14   700000   750000  0.49096
15   750000   800000  0.49622
16   800000   850000  0.49664
17   850000   900000  0.49712
18   900000   950000  0.49524
19   950000  1000000  0.50142
20  1000000  1050000  0.49312
21  1050000  1100000  0.47578
22  1100000  1150000  0.49380
23  1150000  1200000  0.48716
24  1200000  1250000  0.48022
25  1250000  1300000  0.49512
26  1300000  1350000  0.48630
27  1350000  1400000  0.50582
28  1400000  1450000  0.49296
29  1450000  1500000  0.48452
30  1500000  1550000  0.49464
31  1550000  1600000  0.48964
32  1600000  1650000  0.47896
33  1650000  1700000  0.50014
34  1700000  1750000  0.45412
35  1750000  1800000  0.48434
36  1800000  1850000  0.48660
37  1850000  1900000  0.48180
38  1900000  1950000  0.47662
39  1950000  2000000  0.48078
40  2000000  2050000  0.50754
41  2050000  2100000  0.50346
42  2100000  2150000  0.45050
43  2150000  2200000  0.46354
44  2200000  2250000  0.45810
45  2250000  2300000  0.48478
46  2300000  2350000  0.47734
47  2350000  2400000  0.48946
48  2400000  2450000  0.47684
49  2450000  2500000  0.49650
2808376
      start     stop       gc
0         0    50000  0.49250
1     50000   100000  0.47838
2    100000   150000  0.47646
3    150000   200000  0.48254
4    200000   250000  0.48604
5    250000   300000  0.49012
6    300000   350000  0.49084
7    350000   400000  0.49426
8    400000   450000  0.49892
9    450000   500000  0.49412
10   500000   550000  0.48642
11   550000   600000  0.48696
12   600000   650000  0.47616
13   650000   700000  0.48808
14   700000   750000  0.49656
15   750000   800000  0.49274
16   800000   850000  0.49932
17   850000   900000  0.46904
18   900000   950000  0.45572
19   950000  1000000  0.49746
20  1000000  1050000  0.49754
21  1050000  1100000  0.49870
22  1100000  1150000  0.48842
23  1150000  1200000  0.49294
24  1200000  1250000  0.50722
25  1250000  1300000  0.49278
26  1300000  1350000  0.47110
27  1350000  1400000  0.47698
28  1400000  1450000  0.48700
29  1450000  1500000  0.47874
30  1500000  1550000  0.49428
31  1550000  1600000  0.49392
32  1600000  1650000  0.49612
33  1650000  1700000  0.47696
34  1700000  1750000  0.42276
35  1750000  1800000  0.46268
36  1800000  1850000  0.49718
37  1850000  1900000  0.47190
38  1900000  1950000  0.47902
39  1950000  2000000  0.46568
40  2000000  2050000  0.50216
41  2050000  2100000  0.49978
42  2100000  2150000  0.46852
43  2150000  2200000  0.48084
44  2200000  2250000  0.49416
45  2250000  2300000  0.48484
46  2300000  2350000  0.49414
47  2350000  2400000  0.47672
48  2400000  2450000  0.47254
49  2450000  2500000  0.44940
50  2500000  2550000  0.46310
51  2550000  2600000  0.48128
52  2600000  2650000  0.45976
53  2650000  2700000  0.47418
54  2700000  2750000  0.47532
55  2750000  2800000  0.47024
3109985
      start     stop       gc
0         0    50000  0.48820
1     50000   100000  0.49828
2    100000   150000  0.48286
3    150000   200000  0.46012
4    200000   250000  0.47136
..      ...      ...      ...
57  2850000  2900000  0.47524
58  2900000  2950000  0.47174
59  2950000  3000000  0.46464
60  3000000  3050000  0.48388
61  3050000  3100000  0.49172

[62 rows x 3 columns]
3330951
      start     stop       gc
0         0    50000  0.48476
1     50000   100000  0.47886
2    100000   150000  0.49128
3    150000   200000  0.48206
4    200000   250000  0.48278
..      ...      ...      ...
61  3050000  3100000  0.49720
62  3100000  3150000  0.47402
63  3150000  3200000  0.47974
64  3200000  3250000  0.47446
65  3250000  3300000  0.47616

[66 rows x 3 columns]
4100071
      start     stop       gc
0         0    50000  0.47354
1     50000   100000  0.50734
2    100000   150000  0.48436
3    150000   200000  0.49346
4    200000   250000  0.46294
..      ...      ...      ...
77  3850000  3900000  0.47400
78  3900000  3950000  0.47900
79  3950000  4000000  0.46902
80  4000000  4050000  0.43862
81  4050000  4100000  0.46170

[82 rows x 3 columns]
3736295
      start     stop       gc
0         0    50000  0.49470
1     50000   100000  0.48846
2    100000   150000  0.45940
3    150000   200000  0.47626
4    200000   250000  0.44912
..      ...      ...      ...
69  3450000  3500000  0.47286
70  3500000  3550000  0.47876
71  3550000  3600000  0.48412
72  3600000  3650000  0.49202
73  3650000  3700000  0.47030

[74 rows x 3 columns]
3711849
      start     stop       gc
0         0    50000  0.44228
1     50000   100000  0.47630
2    100000   150000  0.49600
3    150000   200000  0.49082
4    200000   250000  0.48428
..      ...      ...      ...
69  3450000  3500000  0.47350
70  3500000  3550000  0.48882
71  3550000  3600000  0.49450
72  3600000  3650000  0.47880
73  3650000  3700000  0.48092

[74 rows x 3 columns]
4221094
      start     stop       gc
0         0    50000  0.49034
1     50000   100000  0.49410
2    100000   150000  0.48412
3    150000   200000  0.48030
4    200000   250000  0.49068
..      ...      ...      ...
79  3950000  4000000  0.47360
80  4000000  4050000  0.46436
81  4050000  4100000  0.45952
82  4100000  4150000  0.46314
83  4150000  4200000  0.45974

[84 rows x 3 columns]
4262825
      start     stop       gc
0         0    50000  0.48700
1     50000   100000  0.46474
2    100000   150000  0.47208
3    150000   200000  0.47230
4    200000   250000  0.48246
..      ...      ...      ...
80  4000000  4050000  0.49000
81  4050000  4100000  0.48044
82  4100000  4150000  0.47364
83  4150000  4200000  0.47880
84  4200000  4250000  0.49066

[85 rows x 3 columns]
4416379
      start     stop       gc
0         0    50000  0.44926
1     50000   100000  0.45558
2    100000   150000  0.42228
3    150000   200000  0.43378
4    200000   250000  0.45338
..      ...      ...      ...
83  4150000  4200000  0.47392
84  4200000  4250000  0.49544
85  4250000  4300000  0.49476
86  4300000  4350000  0.49986
87  4350000  4400000  0.47852

[88 rows x 3 columns]
16

#### Zawartość GC z poziomu terminala

Do szybkiego obliczenia zawartości GC możemy wykorzystać narzędzie **fx2tab** z pakietu **seqkit** korzystając z flag **-n -B GC**. Argumenty flagi **-B** określają nukleotydy, których relatywny udział w sekwencji chcemy określić. Alternatywnie możemy posłużyć się równoważnym **-n -g**

In [20]:
!seqkit fx2tab {in_fasta} -n -B GC

NC_000908.2 Mycoplasmoides genitalium G37, complete sequence	31.69

#### Seqkit umożliwia również analizę w oknie

In [21]:
! cat {in_fasta}| \
 seqkit sliding -s 5000 -W 5000 | \
 seqkit fx2tab -n -g | head

NC_000908.2_sliding:1-5000	28.28
NC_000908.2_sliding:5001-10000	30.54
NC_000908.2_sliding:10001-15000	26.64
NC_000908.2_sliding:15001-20000	29.14
NC_000908.2_sliding:20001-25000	29.52
NC_000908.2_sliding:25001-30000	29.06
NC_000908.2_sliding:30001-35000	30.88
NC_000908.2_sliding:35001-40000	30.32
NC_000908.2_sliding:40001-45000	30.24
NC_000908.2_sliding:45001-50000	31.52

### Wizualizacja Zawartości GC

Dane z poprzednich sekcji zostaną użyte do utworzenia wykresu liniowego, który pokaże zmiany zawartości GC w sekwencji genomu.

In [31]:
for chromname, gcdf in gcdf_dict.items():
    gcplot = (ggplot(gcdf, aes(x="start", y="gc")) + geom_line() + theme_minimal())
    print(gcplot)
    gcplot.save(f"gc_plot_{chromname}.png", width=8, height = 6)

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000007l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000003l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000012l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000008l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000002l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000016l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000018l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000014l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000011l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000015l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000010l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000004l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000001l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000009l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000013l.png

<ggplot: (640 x 480)>

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gc_plot_ptg000017l.png

### Sformatowanie danych do narzędzia Circos

Dane dotyczące zawartości GC zwizualizujemy w postaci histogramu. W tym celu Circos wymaga danych w formacie (bez nagłówka):

|chromosom|start|stop|wartość|kolor|
|--|--|--|--|--|
|Chr1|	0	|100|	1.629407336396254|	fill_color=red|
|Chr1	|100|	200|	1.5523160283080437|	fill_color=red|


#### Dodanie Informacji o Chromosomie


W tej sekcji przypiszemy do naszych danych identyfikator chromosomu.

In [54]:
gcdf_dict_insert = deepcopy(gcdf_dict)

for chromname, gcdf in gcdf_dict.items():
    gcdf.insert(0,"chr",chromname)
    gcdf_dict_insert[chromname] = gcdf
    print(gcdf)

           chr    start     stop       gc
0   ptg000007l        0    50000  0.47702
1   ptg000007l    50000   100000  0.49118
2   ptg000007l   100000   150000  0.47806
3   ptg000007l   150000   200000  0.46692
4   ptg000007l   200000   250000  0.45054
..         ...      ...      ...      ...
94  ptg000007l  4700000  4750000  0.51006
95  ptg000007l  4750000  4800000  0.44950
96  ptg000007l  4800000  4850000  0.50556
97  ptg000007l  4850000  4900000  0.48292
98  ptg000007l  4900000  4950000  0.45106

[99 rows x 4 columns]
           chr    start     stop       gc
0   ptg000003l        0    50000  0.51252
1   ptg000003l    50000   100000  0.48708
2   ptg000003l   100000   150000  0.45720
3   ptg000003l   150000   200000  0.47562
4   ptg000003l   200000   250000  0.48344
5   ptg000003l   250000   300000  0.48452
6   ptg000003l   300000   350000  0.49106
7   ptg000003l   350000   400000  0.49168
8   ptg000003l   400000   450000  0.47088
9   ptg000003l   450000   500000  0.47148
10  ptg000003l   500000   550000  0.50730
11  ptg000003l   550000   600000  0.49122
12  ptg000003l   600000   650000  0.50270
13  ptg000003l   650000   700000  0.49546
14  ptg000003l   700000   750000  0.50182
15  ptg000003l   750000   800000  0.49460
16  ptg000003l   800000   850000  0.42122
17  ptg000003l   850000   900000  0.42900
18  ptg000003l   900000   950000  0.49362
19  ptg000003l   950000  1000000  0.48532
20  ptg000003l  1000000  1050000  0.44674
21  ptg000003l  1050000  1100000  0.47220
22  ptg000003l  1100000  1150000  0.47860
23  ptg000003l  1150000  1200000  0.49196
24  ptg000003l  1200000  1250000  0.49112
25  ptg000003l  1250000  1300000  0.48626
26  ptg000003l  1300000  1350000  0.49164
27  ptg000003l  1350000  1400000  0.48070
28  ptg000003l  1400000  1450000  0.45520
29  ptg000003l  1450000  1500000  0.47410
30  ptg000003l  1500000  1550000  0.47270
31  ptg000003l  1550000  1600000  0.44628
32  ptg000003l  1600000  1650000  0.46284
33  ptg000003l  1650000  1700000  0.47868
34  ptg000003l  1700000  1750000  0.47410
35  ptg000003l  1750000  1800000  0.47882
           chr    start     stop       gc
0   ptg000012l        0    50000  0.48868
1   ptg000012l    50000   100000  0.47428
2   ptg000012l   100000   150000  0.46782
3   ptg000012l   150000   200000  0.47744
4   ptg000012l   200000   250000  0.49376
5   ptg000012l   250000   300000  0.49670
6   ptg000012l   300000   350000  0.48990
7   ptg000012l   350000   400000  0.49128
8   ptg000012l   400000   450000  0.50420
9   ptg000012l   450000   500000  0.49456
10  ptg000012l   500000   550000  0.48360
11  ptg000012l   550000   600000  0.48510
12  ptg000012l   600000   650000  0.49054
13  ptg000012l   650000   700000  0.48908
14  ptg000012l   700000   750000  0.48864
15  ptg000012l   750000   800000  0.48872
16  ptg000012l   800000   850000  0.50524
17  ptg000012l   850000   900000  0.50698
18  ptg000012l   900000   950000  0.46854
19  ptg000012l   950000  1000000  0.48774
20  ptg000012l  1000000  1050000  0.49218
21  ptg000012l  1050000  1100000  0.47674
22  ptg000012l  1100000  1150000  0.46442
23  ptg000012l  1150000  1200000  0.52660
24  ptg000012l  1200000  1250000  0.49242
25  ptg000012l  1250000  1300000  0.50372
26  ptg000012l  1300000  1350000  0.51046
27  ptg000012l  1350000  1400000  0.48354
28  ptg000012l  1400000  1450000  0.49308
29  ptg000012l  1450000  1500000  0.47970
30  ptg000012l  1500000  1550000  0.48700
31  ptg000012l  1550000  1600000  0.48988
32  ptg000012l  1600000  1650000  0.46572
33  ptg000012l  1650000  1700000  0.48220
34  ptg000012l  1700000  1750000  0.48996
35  ptg000012l  1750000  1800000  0.47514
36  ptg000012l  1800000  1850000  0.47388
37  ptg000012l  1850000  1900000  0.46650
38  ptg000012l  1900000  1950000  0.49326
39  ptg000012l  1950000  2000000  0.48294
           chr    start     stop       gc
0   ptg000008l        0    50000  0.48224
1   ptg000008l    50000   100000  0.47114
2   ptg000008l   100000   150000  0.46224
3   ptg000008l   150000   200000  0.48166
4   ptg000008l   200000   250000  0.48534
5   ptg000008l   250000   300000  0.44964
6   ptg000008l   300000   350000  0.45992
7   ptg000008l   350000   400000  0.48562
8   ptg000008l   400000   450000  0.48344
9   ptg000008l   450000   500000  0.49658
10  ptg000008l   500000   550000  0.49962
11  ptg000008l   550000   600000  0.48510
12  ptg000008l   600000   650000  0.49088
13  ptg000008l   650000   700000  0.50954
14  ptg000008l   700000   750000  0.49292
15  ptg000008l   750000   800000  0.48828
16  ptg000008l   800000   850000  0.48774
17  ptg000008l   850000   900000  0.48474
18  ptg000008l   900000   950000  0.48560
19  ptg000008l   950000  1000000  0.45190
20  ptg000008l  1000000  1050000  0.45404
21  ptg000008l  1050000  1100000  0.50412
22  ptg000008l  1100000  1150000  0.48658
23  ptg000008l  1150000  1200000  0.50076
24  ptg000008l  1200000  1250000  0.49878
25  ptg000008l  1250000  1300000  0.49508
26  ptg000008l  1300000  1350000  0.49032
27  ptg000008l  1350000  1400000  0.49124
28  ptg000008l  1400000  1450000  0.50006
29  ptg000008l  1450000  1500000  0.47634
30  ptg000008l  1500000  1550000  0.49002
31  ptg000008l  1550000  1600000  0.48244
32  ptg000008l  1600000  1650000  0.49342
33  ptg000008l  1650000  1700000  0.47970
34  ptg000008l  1700000  1750000  0.50004
35  ptg000008l  1750000  1800000  0.49078
36  ptg000008l  1800000  1850000  0.47426
37  ptg000008l  1850000  1900000  0.49002
38  ptg000008l  1900000  1950000  0.49180
39  ptg000008l  1950000  2000000  0.49638
40  ptg000008l  2000000  2050000  0.46454
41  ptg000008l  2050000  2100000  0.44060
42  ptg000008l  2100000  2150000  0.47500
43  ptg000008l  2150000  2200000  0.46726
44  ptg000008l  2200000  2250000  0.48052
45  ptg000008l  2250000  2300000  0.45070
           chr    start     stop       gc
0   ptg000002l        0    50000  0.48306
1   ptg000002l    50000   100000  0.47240
2   ptg000002l   100000   150000  0.45258
3   ptg000002l   150000   200000  0.46116
4   ptg000002l   200000   250000  0.48144
5   ptg000002l   250000   300000  0.47364
6   ptg000002l   300000   350000  0.46788
7   ptg000002l   350000   400000  0.48014
8   ptg000002l   400000   450000  0.47846
9   ptg000002l   450000   500000  0.48024
10  ptg000002l   500000   550000  0.46442
11  ptg000002l   550000   600000  0.48078
12  ptg000002l   600000   650000  0.49028
13  ptg000002l   650000   700000  0.46910
14  ptg000002l   700000   750000  0.48408
15  ptg000002l   750000   800000  0.48794
16  ptg000002l   800000   850000  0.49096
17  ptg000002l   850000   900000  0.42882
18  ptg000002l   900000   950000  0.42902
19  ptg000002l   950000  1000000  0.48146
20  ptg000002l  1000000  1050000  0.49396
21  ptg000002l  1050000  1100000  0.49620
22  ptg000002l  1100000  1150000  0.50170
23  ptg000002l  1150000  1200000  0.48336
24  ptg000002l  1200000  1250000  0.49464
25  ptg000002l  1250000  1300000  0.49766
26  ptg000002l  1300000  1350000  0.50450
27  ptg000002l  1350000  1400000  0.49260
28  ptg000002l  1400000  1450000  0.47966
29  ptg000002l  1450000  1500000  0.49366
30  ptg000002l  1500000  1550000  0.48950
31  ptg000002l  1550000  1600000  0.50732
32  ptg000002l  1600000  1650000  0.48676
33  ptg000002l  1650000  1700000  0.46544
34  ptg000002l  1700000  1750000  0.49470
35  ptg000002l  1750000  1800000  0.49734
36  ptg000002l  1800000  1850000  0.48882
37  ptg000002l  1850000  1900000  0.47222
38  ptg000002l  1900000  1950000  0.47584
39  ptg000002l  1950000  2000000  0.48928
40  ptg000002l  2000000  2050000  0.48780
41  ptg000002l  2050000  2100000  0.48834
42  ptg000002l  2100000  2150000  0.49232
43  ptg000002l  2150000  2200000  0.49502
44  ptg000002l  2200000  2250000  0.48846
           chr    start     stop       gc
0   ptg000016l        0    50000  0.49180
1   ptg000016l    50000   100000  0.42880
2   ptg000016l   100000   150000  0.50326
3   ptg000016l   150000   200000  0.48894
4   ptg000016l   200000   250000  0.48590
5   ptg000016l   250000   300000  0.49890
6   ptg000016l   300000   350000  0.49284
7   ptg000016l   350000   400000  0.49302
8   ptg000016l   400000   450000  0.48322
9   ptg000016l   450000   500000  0.50524
10  ptg000016l   500000   550000  0.49554
11  ptg000016l   550000   600000  0.48864
12  ptg000016l   600000   650000  0.50380
13  ptg000016l   650000   700000  0.49122
14  ptg000016l   700000   750000  0.48922
15  ptg000016l   750000   800000  0.49240
16  ptg000016l   800000   850000  0.50226
17  ptg000016l   850000   900000  0.50514
18  ptg000016l   900000   950000  0.49770
19  ptg000016l   950000  1000000  0.49360
20  ptg000016l  1000000  1050000  0.49928
21  ptg000016l  1050000  1100000  0.49890
22  ptg000016l  1100000  1150000  0.49680
23  ptg000016l  1150000  1200000  0.49648
24  ptg000016l  1200000  1250000  0.46400
25  ptg000016l  1250000  1300000  0.48156
26  ptg000016l  1300000  1350000  0.49246
27  ptg000016l  1350000  1400000  0.50388
28  ptg000016l  1400000  1450000  0.48664
29  ptg000016l  1450000  1500000  0.49078
30  ptg000016l  1500000  1550000  0.49666
31  ptg000016l  1550000  1600000  0.50022
32  ptg000016l  1600000  1650000  0.48808
33  ptg000016l  1650000  1700000  0.48260
34  ptg000016l  1700000  1750000  0.50464
35  ptg000016l  1750000  1800000  0.49584
36  ptg000016l  1800000  1850000  0.47838
37  ptg000016l  1850000  1900000  0.48966
38  ptg000016l  1900000  1950000  0.48514
39  ptg000016l  1950000  2000000  0.48726
40  ptg000016l  2000000  2050000  0.48160
41  ptg000016l  2050000  2100000  0.50218
42  ptg000016l  2100000  2150000  0.47670
43  ptg000016l  2150000  2200000  0.48432
44  ptg000016l  2200000  2250000  0.48714
45  ptg000016l  2250000  2300000  0.42568
           chr    start     stop       gc
0   ptg000018l        0    50000  0.46076
1   ptg000018l    50000   100000  0.44424
2   ptg000018l   100000   150000  0.46586
3   ptg000018l   150000   200000  0.49480
4   ptg000018l   200000   250000  0.48938
5   ptg000018l   250000   300000  0.50382
6   ptg000018l   300000   350000  0.49172
7   ptg000018l   350000   400000  0.48780
8   ptg000018l   400000   450000  0.48614
9   ptg000018l   450000   500000  0.49616
10  ptg000018l   500000   550000  0.48128
11  ptg000018l   550000   600000  0.49710
12  ptg000018l   600000   650000  0.50326
13  ptg000018l   650000   700000  0.48994
14  ptg000018l   700000   750000  0.49096
15  ptg000018l   750000   800000  0.49622
16  ptg000018l   800000   850000  0.49664
17  ptg000018l   850000   900000  0.49712
18  ptg000018l   900000   950000  0.49524
19  ptg000018l   950000  1000000  0.50142
20  ptg000018l  1000000  1050000  0.49312
21  ptg000018l  1050000  1100000  0.47578
22  ptg000018l  1100000  1150000  0.49380
23  ptg000018l  1150000  1200000  0.48716
24  ptg000018l  1200000  1250000  0.48022
25  ptg000018l  1250000  1300000  0.49512
26  ptg000018l  1300000  1350000  0.48630
27  ptg000018l  1350000  1400000  0.50582
28  ptg000018l  1400000  1450000  0.49296
29  ptg000018l  1450000  1500000  0.48452
30  ptg000018l  1500000  1550000  0.49464
31  ptg000018l  1550000  1600000  0.48964
32  ptg000018l  1600000  1650000  0.47896
33  ptg000018l  1650000  1700000  0.50014
34  ptg000018l  1700000  1750000  0.45412
35  ptg000018l  1750000  1800000  0.48434
36  ptg000018l  1800000  1850000  0.48660
37  ptg000018l  1850000  1900000  0.48180
38  ptg000018l  1900000  1950000  0.47662
39  ptg000018l  1950000  2000000  0.48078
40  ptg000018l  2000000  2050000  0.50754
41  ptg000018l  2050000  2100000  0.50346
42  ptg000018l  2100000  2150000  0.45050
43  ptg000018l  2150000  2200000  0.46354
44  ptg000018l  2200000  2250000  0.45810
45  ptg000018l  2250000  2300000  0.48478
46  ptg000018l  2300000  2350000  0.47734
47  ptg000018l  2350000  2400000  0.48946
48  ptg000018l  2400000  2450000  0.47684
49  ptg000018l  2450000  2500000  0.49650
           chr    start     stop       gc
0   ptg000014l        0    50000  0.49250
1   ptg000014l    50000   100000  0.47838
2   ptg000014l   100000   150000  0.47646
3   ptg000014l   150000   200000  0.48254
4   ptg000014l   200000   250000  0.48604
5   ptg000014l   250000   300000  0.49012
6   ptg000014l   300000   350000  0.49084
7   ptg000014l   350000   400000  0.49426
8   ptg000014l   400000   450000  0.49892
9   ptg000014l   450000   500000  0.49412
10  ptg000014l   500000   550000  0.48642
11  ptg000014l   550000   600000  0.48696
12  ptg000014l   600000   650000  0.47616
13  ptg000014l   650000   700000  0.48808
14  ptg000014l   700000   750000  0.49656
15  ptg000014l   750000   800000  0.49274
16  ptg000014l   800000   850000  0.49932
17  ptg000014l   850000   900000  0.46904
18  ptg000014l   900000   950000  0.45572
19  ptg000014l   950000  1000000  0.49746
20  ptg000014l  1000000  1050000  0.49754
21  ptg000014l  1050000  1100000  0.49870
22  ptg000014l  1100000  1150000  0.48842
23  ptg000014l  1150000  1200000  0.49294
24  ptg000014l  1200000  1250000  0.50722
25  ptg000014l  1250000  1300000  0.49278
26  ptg000014l  1300000  1350000  0.47110
27  ptg000014l  1350000  1400000  0.47698
28  ptg000014l  1400000  1450000  0.48700
29  ptg000014l  1450000  1500000  0.47874
30  ptg000014l  1500000  1550000  0.49428
31  ptg000014l  1550000  1600000  0.49392
32  ptg000014l  1600000  1650000  0.49612
33  ptg000014l  1650000  1700000  0.47696
34  ptg000014l  1700000  1750000  0.42276
35  ptg000014l  1750000  1800000  0.46268
36  ptg000014l  1800000  1850000  0.49718
37  ptg000014l  1850000  1900000  0.47190
38  ptg000014l  1900000  1950000  0.47902
39  ptg000014l  1950000  2000000  0.46568
40  ptg000014l  2000000  2050000  0.50216
41  ptg000014l  2050000  2100000  0.49978
42  ptg000014l  2100000  2150000  0.46852
43  ptg000014l  2150000  2200000  0.48084
44  ptg000014l  2200000  2250000  0.49416
45  ptg000014l  2250000  2300000  0.48484
46  ptg000014l  2300000  2350000  0.49414
47  ptg000014l  2350000  2400000  0.47672
48  ptg000014l  2400000  2450000  0.47254
49  ptg000014l  2450000  2500000  0.44940
50  ptg000014l  2500000  2550000  0.46310
51  ptg000014l  2550000  2600000  0.48128
52  ptg000014l  2600000  2650000  0.45976
53  ptg000014l  2650000  2700000  0.47418
54  ptg000014l  2700000  2750000  0.47532
55  ptg000014l  2750000  2800000  0.47024
           chr    start     stop       gc
0   ptg000011l        0    50000  0.48820
1   ptg000011l    50000   100000  0.49828
2   ptg000011l   100000   150000  0.48286
3   ptg000011l   150000   200000  0.46012
4   ptg000011l   200000   250000  0.47136
..         ...      ...      ...      ...
57  ptg000011l  2850000  2900000  0.47524
58  ptg000011l  2900000  2950000  0.47174
59  ptg000011l  2950000  3000000  0.46464
60  ptg000011l  3000000  3050000  0.48388
61  ptg000011l  3050000  3100000  0.49172

[62 rows x 4 columns]
           chr    start     stop       gc
0   ptg000015l        0    50000  0.48476
1   ptg000015l    50000   100000  0.47886
2   ptg000015l   100000   150000  0.49128
3   ptg000015l   150000   200000  0.48206
4   ptg000015l   200000   250000  0.48278
..         ...      ...      ...      ...
61  ptg000015l  3050000  3100000  0.49720
62  ptg000015l  3100000  3150000  0.47402
63  ptg000015l  3150000  3200000  0.47974
64  ptg000015l  3200000  3250000  0.47446
65  ptg000015l  3250000  3300000  0.47616

[66 rows x 4 columns]
           chr    start     stop       gc
0   ptg000010l        0    50000  0.47354
1   ptg000010l    50000   100000  0.50734
2   ptg000010l   100000   150000  0.48436
3   ptg000010l   150000   200000  0.49346
4   ptg000010l   200000   250000  0.46294
..         ...      ...      ...      ...
77  ptg000010l  3850000  3900000  0.47400
78  ptg000010l  3900000  3950000  0.47900
79  ptg000010l  3950000  4000000  0.46902
80  ptg000010l  4000000  4050000  0.43862
81  ptg000010l  4050000  4100000  0.46170

[82 rows x 4 columns]
           chr    start     stop       gc
0   ptg000004l        0    50000  0.49470
1   ptg000004l    50000   100000  0.48846
2   ptg000004l   100000   150000  0.45940
3   ptg000004l   150000   200000  0.47626
4   ptg000004l   200000   250000  0.44912
..         ...      ...      ...      ...
69  ptg000004l  3450000  3500000  0.47286
70  ptg000004l  3500000  3550000  0.47876
71  ptg000004l  3550000  3600000  0.48412
72  ptg000004l  3600000  3650000  0.49202
73  ptg000004l  3650000  3700000  0.47030

[74 rows x 4 columns]
           chr    start     stop       gc
0   ptg000001l        0    50000  0.44228
1   ptg000001l    50000   100000  0.47630
2   ptg000001l   100000   150000  0.49600
3   ptg000001l   150000   200000  0.49082
4   ptg000001l   200000   250000  0.48428
..         ...      ...      ...      ...
69  ptg000001l  3450000  3500000  0.47350
70  ptg000001l  3500000  3550000  0.48882
71  ptg000001l  3550000  3600000  0.49450
72  ptg000001l  3600000  3650000  0.47880
73  ptg000001l  3650000  3700000  0.48092

[74 rows x 4 columns]
           chr    start     stop       gc
0   ptg000009l        0    50000  0.49034
1   ptg000009l    50000   100000  0.49410
2   ptg000009l   100000   150000  0.48412
3   ptg000009l   150000   200000  0.48030
4   ptg000009l   200000   250000  0.49068
..         ...      ...      ...      ...
79  ptg000009l  3950000  4000000  0.47360
80  ptg000009l  4000000  4050000  0.46436
81  ptg000009l  4050000  4100000  0.45952
82  ptg000009l  4100000  4150000  0.46314
83  ptg000009l  4150000  4200000  0.45974

[84 rows x 4 columns]
           chr    start     stop       gc
0   ptg000013l        0    50000  0.48700
1   ptg000013l    50000   100000  0.46474
2   ptg000013l   100000   150000  0.47208
3   ptg000013l   150000   200000  0.47230
4   ptg000013l   200000   250000  0.48246
..         ...      ...      ...      ...
80  ptg000013l  4000000  4050000  0.49000
81  ptg000013l  4050000  4100000  0.48044
82  ptg000013l  4100000  4150000  0.47364
83  ptg000013l  4150000  4200000  0.47880
84  ptg000013l  4200000  4250000  0.49066

[85 rows x 4 columns]
           chr    start     stop       gc
0   ptg000017l        0    50000  0.44926
1   ptg000017l    50000   100000  0.45558
2   ptg000017l   100000   150000  0.42228
3   ptg000017l   150000   200000  0.43378
4   ptg000017l   200000   250000  0.45338
..         ...      ...      ...      ...
83  ptg000017l  4150000  4200000  0.47392
84  ptg000017l  4200000  4250000  0.49544
85  ptg000017l  4250000  4300000  0.49476
86  ptg000017l  4300000  4350000  0.49986
87  ptg000017l  4350000  4400000  0.47852

[88 rows x 4 columns]

#### Przypisanie Kolorów do Zakresów GC
W tej części przypiszemy kolory do różnych zakresów zawartości GC. W zależności od wartości zawartości GC, zakresy te otrzymają różne kolory na wykresie. Kolory określimy w formacie "R,G,B".

In [55]:
gcdf_dict_final = deepcopy(gcdf_dict_insert)

for chromname, gcdf in gcdf_dict_insert.items():
    # Definiujemy przedziały (bins) oraz odpowiadające im etykiety kolorów
    bins = [0, 0.25, 0.35, float('inf')]
    colors = ["fill_color=103,201,129", "fill_color=201,193,103", "fill_color=204,116,92"]

    # Używamy pd.cut do zaklasyfikowania wartości w kolumnie 'gc' i przypisania odpowiednich etykiet na podstawie przedziałów
    gcdf['col'] = pd.cut(gcdf['gc'], bins=bins, labels=colors, right=True)
    gcdf_dict_final[chromname] = gcdf
    print(gcdf)

           chr    start     stop       gc                    col
0   ptg000007l        0    50000  0.47702  fill_color=204,116,92
1   ptg000007l    50000   100000  0.49118  fill_color=204,116,92
2   ptg000007l   100000   150000  0.47806  fill_color=204,116,92
3   ptg000007l   150000   200000  0.46692  fill_color=204,116,92
4   ptg000007l   200000   250000  0.45054  fill_color=204,116,92
..         ...      ...      ...      ...                    ...
94  ptg000007l  4700000  4750000  0.51006  fill_color=204,116,92
95  ptg000007l  4750000  4800000  0.44950  fill_color=204,116,92
96  ptg000007l  4800000  4850000  0.50556  fill_color=204,116,92
97  ptg000007l  4850000  4900000  0.48292  fill_color=204,116,92
98  ptg000007l  4900000  4950000  0.45106  fill_color=204,116,92

[99 rows x 5 columns]
           chr    start     stop       gc                    col
0   ptg000003l        0    50000  0.51252  fill_color=204,116,92
1   ptg000003l    50000   100000  0.48708  fill_color=204,116,92
2   ptg000003l   100000   150000  0.45720  fill_color=204,116,92
3   ptg000003l   150000   200000  0.47562  fill_color=204,116,92
4   ptg000003l   200000   250000  0.48344  fill_color=204,116,92
5   ptg000003l   250000   300000  0.48452  fill_color=204,116,92
6   ptg000003l   300000   350000  0.49106  fill_color=204,116,92
7   ptg000003l   350000   400000  0.49168  fill_color=204,116,92
8   ptg000003l   400000   450000  0.47088  fill_color=204,116,92
9   ptg000003l   450000   500000  0.47148  fill_color=204,116,92
10  ptg000003l   500000   550000  0.50730  fill_color=204,116,92
11  ptg000003l   550000   600000  0.49122  fill_color=204,116,92
12  ptg000003l   600000   650000  0.50270  fill_color=204,116,92
13  ptg000003l   650000   700000  0.49546  fill_color=204,116,92
14  ptg000003l   700000   750000  0.50182  fill_color=204,116,92
15  ptg000003l   750000   800000  0.49460  fill_color=204,116,92
16  ptg000003l   800000   850000  0.42122  fill_color=204,116,92
17  ptg000003l   850000   900000  0.42900  fill_color=204,116,92
18  ptg000003l   900000   950000  0.49362  fill_color=204,116,92
19  ptg000003l   950000  1000000  0.48532  fill_color=204,116,92
20  ptg000003l  1000000  1050000  0.44674  fill_color=204,116,92
21  ptg000003l  1050000  1100000  0.47220  fill_color=204,116,92
22  ptg000003l  1100000  1150000  0.47860  fill_color=204,116,92
23  ptg000003l  1150000  1200000  0.49196  fill_color=204,116,92
24  ptg000003l  1200000  1250000  0.49112  fill_color=204,116,92
25  ptg000003l  1250000  1300000  0.48626  fill_color=204,116,92
26  ptg000003l  1300000  1350000  0.49164  fill_color=204,116,92
27  ptg000003l  1350000  1400000  0.48070  fill_color=204,116,92
28  ptg000003l  1400000  1450000  0.45520  fill_color=204,116,92
29  ptg000003l  1450000  1500000  0.47410  fill_color=204,116,92
30  ptg000003l  1500000  1550000  0.47270  fill_color=204,116,92
31  ptg000003l  1550000  1600000  0.44628  fill_color=204,116,92
32  ptg000003l  1600000  1650000  0.46284  fill_color=204,116,92
33  ptg000003l  1650000  1700000  0.47868  fill_color=204,116,92
34  ptg000003l  1700000  1750000  0.47410  fill_color=204,116,92
35  ptg000003l  1750000  1800000  0.47882  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000012l        0    50000  0.48868  fill_color=204,116,92
1   ptg000012l    50000   100000  0.47428  fill_color=204,116,92
2   ptg000012l   100000   150000  0.46782  fill_color=204,116,92
3   ptg000012l   150000   200000  0.47744  fill_color=204,116,92
4   ptg000012l   200000   250000  0.49376  fill_color=204,116,92
5   ptg000012l   250000   300000  0.49670  fill_color=204,116,92
6   ptg000012l   300000   350000  0.48990  fill_color=204,116,92
7   ptg000012l   350000   400000  0.49128  fill_color=204,116,92
8   ptg000012l   400000   450000  0.50420  fill_color=204,116,92
9   ptg000012l   450000   500000  0.49456  fill_color=204,116,92
10  ptg000012l   500000   550000  0.48360  fill_color=204,116,92
11  ptg000012l   550000   600000  0.48510  fill_color=204,116,92
12  ptg000012l   600000   650000  0.49054  fill_color=204,116,92
13  ptg000012l   650000   700000  0.48908  fill_color=204,116,92
14  ptg000012l   700000   750000  0.48864  fill_color=204,116,92
15  ptg000012l   750000   800000  0.48872  fill_color=204,116,92
16  ptg000012l   800000   850000  0.50524  fill_color=204,116,92
17  ptg000012l   850000   900000  0.50698  fill_color=204,116,92
18  ptg000012l   900000   950000  0.46854  fill_color=204,116,92
19  ptg000012l   950000  1000000  0.48774  fill_color=204,116,92
20  ptg000012l  1000000  1050000  0.49218  fill_color=204,116,92
21  ptg000012l  1050000  1100000  0.47674  fill_color=204,116,92
22  ptg000012l  1100000  1150000  0.46442  fill_color=204,116,92
23  ptg000012l  1150000  1200000  0.52660  fill_color=204,116,92
24  ptg000012l  1200000  1250000  0.49242  fill_color=204,116,92
25  ptg000012l  1250000  1300000  0.50372  fill_color=204,116,92
26  ptg000012l  1300000  1350000  0.51046  fill_color=204,116,92
27  ptg000012l  1350000  1400000  0.48354  fill_color=204,116,92
28  ptg000012l  1400000  1450000  0.49308  fill_color=204,116,92
29  ptg000012l  1450000  1500000  0.47970  fill_color=204,116,92
30  ptg000012l  1500000  1550000  0.48700  fill_color=204,116,92
31  ptg000012l  1550000  1600000  0.48988  fill_color=204,116,92
32  ptg000012l  1600000  1650000  0.46572  fill_color=204,116,92
33  ptg000012l  1650000  1700000  0.48220  fill_color=204,116,92
34  ptg000012l  1700000  1750000  0.48996  fill_color=204,116,92
35  ptg000012l  1750000  1800000  0.47514  fill_color=204,116,92
36  ptg000012l  1800000  1850000  0.47388  fill_color=204,116,92
37  ptg000012l  1850000  1900000  0.46650  fill_color=204,116,92
38  ptg000012l  1900000  1950000  0.49326  fill_color=204,116,92
39  ptg000012l  1950000  2000000  0.48294  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000008l        0    50000  0.48224  fill_color=204,116,92
1   ptg000008l    50000   100000  0.47114  fill_color=204,116,92
2   ptg000008l   100000   150000  0.46224  fill_color=204,116,92
3   ptg000008l   150000   200000  0.48166  fill_color=204,116,92
4   ptg000008l   200000   250000  0.48534  fill_color=204,116,92
5   ptg000008l   250000   300000  0.44964  fill_color=204,116,92
6   ptg000008l   300000   350000  0.45992  fill_color=204,116,92
7   ptg000008l   350000   400000  0.48562  fill_color=204,116,92
8   ptg000008l   400000   450000  0.48344  fill_color=204,116,92
9   ptg000008l   450000   500000  0.49658  fill_color=204,116,92
10  ptg000008l   500000   550000  0.49962  fill_color=204,116,92
11  ptg000008l   550000   600000  0.48510  fill_color=204,116,92
12  ptg000008l   600000   650000  0.49088  fill_color=204,116,92
13  ptg000008l   650000   700000  0.50954  fill_color=204,116,92
14  ptg000008l   700000   750000  0.49292  fill_color=204,116,92
15  ptg000008l   750000   800000  0.48828  fill_color=204,116,92
16  ptg000008l   800000   850000  0.48774  fill_color=204,116,92
17  ptg000008l   850000   900000  0.48474  fill_color=204,116,92
18  ptg000008l   900000   950000  0.48560  fill_color=204,116,92
19  ptg000008l   950000  1000000  0.45190  fill_color=204,116,92
20  ptg000008l  1000000  1050000  0.45404  fill_color=204,116,92
21  ptg000008l  1050000  1100000  0.50412  fill_color=204,116,92
22  ptg000008l  1100000  1150000  0.48658  fill_color=204,116,92
23  ptg000008l  1150000  1200000  0.50076  fill_color=204,116,92
24  ptg000008l  1200000  1250000  0.49878  fill_color=204,116,92
25  ptg000008l  1250000  1300000  0.49508  fill_color=204,116,92
26  ptg000008l  1300000  1350000  0.49032  fill_color=204,116,92
27  ptg000008l  1350000  1400000  0.49124  fill_color=204,116,92
28  ptg000008l  1400000  1450000  0.50006  fill_color=204,116,92
29  ptg000008l  1450000  1500000  0.47634  fill_color=204,116,92
30  ptg000008l  1500000  1550000  0.49002  fill_color=204,116,92
31  ptg000008l  1550000  1600000  0.48244  fill_color=204,116,92
32  ptg000008l  1600000  1650000  0.49342  fill_color=204,116,92
33  ptg000008l  1650000  1700000  0.47970  fill_color=204,116,92
34  ptg000008l  1700000  1750000  0.50004  fill_color=204,116,92
35  ptg000008l  1750000  1800000  0.49078  fill_color=204,116,92
36  ptg000008l  1800000  1850000  0.47426  fill_color=204,116,92
37  ptg000008l  1850000  1900000  0.49002  fill_color=204,116,92
38  ptg000008l  1900000  1950000  0.49180  fill_color=204,116,92
39  ptg000008l  1950000  2000000  0.49638  fill_color=204,116,92
40  ptg000008l  2000000  2050000  0.46454  fill_color=204,116,92
41  ptg000008l  2050000  2100000  0.44060  fill_color=204,116,92
42  ptg000008l  2100000  2150000  0.47500  fill_color=204,116,92
43  ptg000008l  2150000  2200000  0.46726  fill_color=204,116,92
44  ptg000008l  2200000  2250000  0.48052  fill_color=204,116,92
45  ptg000008l  2250000  2300000  0.45070  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000002l        0    50000  0.48306  fill_color=204,116,92
1   ptg000002l    50000   100000  0.47240  fill_color=204,116,92
2   ptg000002l   100000   150000  0.45258  fill_color=204,116,92
3   ptg000002l   150000   200000  0.46116  fill_color=204,116,92
4   ptg000002l   200000   250000  0.48144  fill_color=204,116,92
5   ptg000002l   250000   300000  0.47364  fill_color=204,116,92
6   ptg000002l   300000   350000  0.46788  fill_color=204,116,92
7   ptg000002l   350000   400000  0.48014  fill_color=204,116,92
8   ptg000002l   400000   450000  0.47846  fill_color=204,116,92
9   ptg000002l   450000   500000  0.48024  fill_color=204,116,92
10  ptg000002l   500000   550000  0.46442  fill_color=204,116,92
11  ptg000002l   550000   600000  0.48078  fill_color=204,116,92
12  ptg000002l   600000   650000  0.49028  fill_color=204,116,92
13  ptg000002l   650000   700000  0.46910  fill_color=204,116,92
14  ptg000002l   700000   750000  0.48408  fill_color=204,116,92
15  ptg000002l   750000   800000  0.48794  fill_color=204,116,92
16  ptg000002l   800000   850000  0.49096  fill_color=204,116,92
17  ptg000002l   850000   900000  0.42882  fill_color=204,116,92
18  ptg000002l   900000   950000  0.42902  fill_color=204,116,92
19  ptg000002l   950000  1000000  0.48146  fill_color=204,116,92
20  ptg000002l  1000000  1050000  0.49396  fill_color=204,116,92
21  ptg000002l  1050000  1100000  0.49620  fill_color=204,116,92
22  ptg000002l  1100000  1150000  0.50170  fill_color=204,116,92
23  ptg000002l  1150000  1200000  0.48336  fill_color=204,116,92
24  ptg000002l  1200000  1250000  0.49464  fill_color=204,116,92
25  ptg000002l  1250000  1300000  0.49766  fill_color=204,116,92
26  ptg000002l  1300000  1350000  0.50450  fill_color=204,116,92
27  ptg000002l  1350000  1400000  0.49260  fill_color=204,116,92
28  ptg000002l  1400000  1450000  0.47966  fill_color=204,116,92
29  ptg000002l  1450000  1500000  0.49366  fill_color=204,116,92
30  ptg000002l  1500000  1550000  0.48950  fill_color=204,116,92
31  ptg000002l  1550000  1600000  0.50732  fill_color=204,116,92
32  ptg000002l  1600000  1650000  0.48676  fill_color=204,116,92
33  ptg000002l  1650000  1700000  0.46544  fill_color=204,116,92
34  ptg000002l  1700000  1750000  0.49470  fill_color=204,116,92
35  ptg000002l  1750000  1800000  0.49734  fill_color=204,116,92
36  ptg000002l  1800000  1850000  0.48882  fill_color=204,116,92
37  ptg000002l  1850000  1900000  0.47222  fill_color=204,116,92
38  ptg000002l  1900000  1950000  0.47584  fill_color=204,116,92
39  ptg000002l  1950000  2000000  0.48928  fill_color=204,116,92
40  ptg000002l  2000000  2050000  0.48780  fill_color=204,116,92
41  ptg000002l  2050000  2100000  0.48834  fill_color=204,116,92
42  ptg000002l  2100000  2150000  0.49232  fill_color=204,116,92
43  ptg000002l  2150000  2200000  0.49502  fill_color=204,116,92
44  ptg000002l  2200000  2250000  0.48846  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000016l        0    50000  0.49180  fill_color=204,116,92
1   ptg000016l    50000   100000  0.42880  fill_color=204,116,92
2   ptg000016l   100000   150000  0.50326  fill_color=204,116,92
3   ptg000016l   150000   200000  0.48894  fill_color=204,116,92
4   ptg000016l   200000   250000  0.48590  fill_color=204,116,92
5   ptg000016l   250000   300000  0.49890  fill_color=204,116,92
6   ptg000016l   300000   350000  0.49284  fill_color=204,116,92
7   ptg000016l   350000   400000  0.49302  fill_color=204,116,92
8   ptg000016l   400000   450000  0.48322  fill_color=204,116,92
9   ptg000016l   450000   500000  0.50524  fill_color=204,116,92
10  ptg000016l   500000   550000  0.49554  fill_color=204,116,92
11  ptg000016l   550000   600000  0.48864  fill_color=204,116,92
12  ptg000016l   600000   650000  0.50380  fill_color=204,116,92
13  ptg000016l   650000   700000  0.49122  fill_color=204,116,92
14  ptg000016l   700000   750000  0.48922  fill_color=204,116,92
15  ptg000016l   750000   800000  0.49240  fill_color=204,116,92
16  ptg000016l   800000   850000  0.50226  fill_color=204,116,92
17  ptg000016l   850000   900000  0.50514  fill_color=204,116,92
18  ptg000016l   900000   950000  0.49770  fill_color=204,116,92
19  ptg000016l   950000  1000000  0.49360  fill_color=204,116,92
20  ptg000016l  1000000  1050000  0.49928  fill_color=204,116,92
21  ptg000016l  1050000  1100000  0.49890  fill_color=204,116,92
22  ptg000016l  1100000  1150000  0.49680  fill_color=204,116,92
23  ptg000016l  1150000  1200000  0.49648  fill_color=204,116,92
24  ptg000016l  1200000  1250000  0.46400  fill_color=204,116,92
25  ptg000016l  1250000  1300000  0.48156  fill_color=204,116,92
26  ptg000016l  1300000  1350000  0.49246  fill_color=204,116,92
27  ptg000016l  1350000  1400000  0.50388  fill_color=204,116,92
28  ptg000016l  1400000  1450000  0.48664  fill_color=204,116,92
29  ptg000016l  1450000  1500000  0.49078  fill_color=204,116,92
30  ptg000016l  1500000  1550000  0.49666  fill_color=204,116,92
31  ptg000016l  1550000  1600000  0.50022  fill_color=204,116,92
32  ptg000016l  1600000  1650000  0.48808  fill_color=204,116,92
33  ptg000016l  1650000  1700000  0.48260  fill_color=204,116,92
34  ptg000016l  1700000  1750000  0.50464  fill_color=204,116,92
35  ptg000016l  1750000  1800000  0.49584  fill_color=204,116,92
36  ptg000016l  1800000  1850000  0.47838  fill_color=204,116,92
37  ptg000016l  1850000  1900000  0.48966  fill_color=204,116,92
38  ptg000016l  1900000  1950000  0.48514  fill_color=204,116,92
39  ptg000016l  1950000  2000000  0.48726  fill_color=204,116,92
40  ptg000016l  2000000  2050000  0.48160  fill_color=204,116,92
41  ptg000016l  2050000  2100000  0.50218  fill_color=204,116,92
42  ptg000016l  2100000  2150000  0.47670  fill_color=204,116,92
43  ptg000016l  2150000  2200000  0.48432  fill_color=204,116,92
44  ptg000016l  2200000  2250000  0.48714  fill_color=204,116,92
45  ptg000016l  2250000  2300000  0.42568  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000018l        0    50000  0.46076  fill_color=204,116,92
1   ptg000018l    50000   100000  0.44424  fill_color=204,116,92
2   ptg000018l   100000   150000  0.46586  fill_color=204,116,92
3   ptg000018l   150000   200000  0.49480  fill_color=204,116,92
4   ptg000018l   200000   250000  0.48938  fill_color=204,116,92
5   ptg000018l   250000   300000  0.50382  fill_color=204,116,92
6   ptg000018l   300000   350000  0.49172  fill_color=204,116,92
7   ptg000018l   350000   400000  0.48780  fill_color=204,116,92
8   ptg000018l   400000   450000  0.48614  fill_color=204,116,92
9   ptg000018l   450000   500000  0.49616  fill_color=204,116,92
10  ptg000018l   500000   550000  0.48128  fill_color=204,116,92
11  ptg000018l   550000   600000  0.49710  fill_color=204,116,92
12  ptg000018l   600000   650000  0.50326  fill_color=204,116,92
13  ptg000018l   650000   700000  0.48994  fill_color=204,116,92
14  ptg000018l   700000   750000  0.49096  fill_color=204,116,92
15  ptg000018l   750000   800000  0.49622  fill_color=204,116,92
16  ptg000018l   800000   850000  0.49664  fill_color=204,116,92
17  ptg000018l   850000   900000  0.49712  fill_color=204,116,92
18  ptg000018l   900000   950000  0.49524  fill_color=204,116,92
19  ptg000018l   950000  1000000  0.50142  fill_color=204,116,92
20  ptg000018l  1000000  1050000  0.49312  fill_color=204,116,92
21  ptg000018l  1050000  1100000  0.47578  fill_color=204,116,92
22  ptg000018l  1100000  1150000  0.49380  fill_color=204,116,92
23  ptg000018l  1150000  1200000  0.48716  fill_color=204,116,92
24  ptg000018l  1200000  1250000  0.48022  fill_color=204,116,92
25  ptg000018l  1250000  1300000  0.49512  fill_color=204,116,92
26  ptg000018l  1300000  1350000  0.48630  fill_color=204,116,92
27  ptg000018l  1350000  1400000  0.50582  fill_color=204,116,92
28  ptg000018l  1400000  1450000  0.49296  fill_color=204,116,92
29  ptg000018l  1450000  1500000  0.48452  fill_color=204,116,92
30  ptg000018l  1500000  1550000  0.49464  fill_color=204,116,92
31  ptg000018l  1550000  1600000  0.48964  fill_color=204,116,92
32  ptg000018l  1600000  1650000  0.47896  fill_color=204,116,92
33  ptg000018l  1650000  1700000  0.50014  fill_color=204,116,92
34  ptg000018l  1700000  1750000  0.45412  fill_color=204,116,92
35  ptg000018l  1750000  1800000  0.48434  fill_color=204,116,92
36  ptg000018l  1800000  1850000  0.48660  fill_color=204,116,92
37  ptg000018l  1850000  1900000  0.48180  fill_color=204,116,92
38  ptg000018l  1900000  1950000  0.47662  fill_color=204,116,92
39  ptg000018l  1950000  2000000  0.48078  fill_color=204,116,92
40  ptg000018l  2000000  2050000  0.50754  fill_color=204,116,92
41  ptg000018l  2050000  2100000  0.50346  fill_color=204,116,92
42  ptg000018l  2100000  2150000  0.45050  fill_color=204,116,92
43  ptg000018l  2150000  2200000  0.46354  fill_color=204,116,92
44  ptg000018l  2200000  2250000  0.45810  fill_color=204,116,92
45  ptg000018l  2250000  2300000  0.48478  fill_color=204,116,92
46  ptg000018l  2300000  2350000  0.47734  fill_color=204,116,92
47  ptg000018l  2350000  2400000  0.48946  fill_color=204,116,92
48  ptg000018l  2400000  2450000  0.47684  fill_color=204,116,92
49  ptg000018l  2450000  2500000  0.49650  fill_color=204,116,92
           chr    start     stop       gc                    col
0   ptg000014l        0    50000  0.49250  fill_color=204,116,92
1   ptg000014l    50000   100000  0.47838  fill_color=204,116,92
2   ptg000014l   100000   150000  0.47646  fill_color=204,116,92
3   ptg000014l   150000   200000  0.48254  fill_color=204,116,92
4   ptg000014l   200000   250000  0.48604  fill_color=204,116,92
5   ptg000014l   250000   300000  0.49012  fill_color=204,116,92
6   ptg000014l   300000   350000  0.49084  fill_color=204,116,92
7   ptg000014l   350000   400000  0.49426  fill_color=204,116,92
8   ptg000014l   400000   450000  0.49892  fill_color=204,116,92
9   ptg000014l   450000   500000  0.49412  fill_color=204,116,92
10  ptg000014l   500000   550000  0.48642  fill_color=204,116,92
11  ptg000014l   550000   600000  0.48696  fill_color=204,116,92
12  ptg000014l   600000   650000  0.47616  fill_color=204,116,92
13  ptg000014l   650000   700000  0.48808  fill_color=204,116,92
14  ptg000014l   700000   750000  0.49656  fill_color=204,116,92
15  ptg000014l   750000   800000  0.49274  fill_color=204,116,92
16  ptg000014l   800000   850000  0.49932  fill_color=204,116,92
17  ptg000014l   850000   900000  0.46904  fill_color=204,116,92
18  ptg000014l   900000   950000  0.45572  fill_color=204,116,92
19  ptg000014l   950000  1000000  0.49746  fill_color=204,116,92
20  ptg000014l  1000000  1050000  0.49754  fill_color=204,116,92
21  ptg000014l  1050000  1100000  0.49870  fill_color=204,116,92
22  ptg000014l  1100000  1150000  0.48842  fill_color=204,116,92
23  ptg000014l  1150000  1200000  0.49294  fill_color=204,116,92
24  ptg000014l  1200000  1250000  0.50722  fill_color=204,116,92

#### Zapisywanie Danych

Teraz, gdy przeprowadziliśmy analizę zawartości GC, przypisaliśmy kolory i dodaliśmy informacje o chromosomie, zapiszemy te dane do pliku.

In [39]:
for chromname, gcdf in gcdf_dict_final.items():
    gcdf.to_csv(f"gc_content_{chromname}.histo", sep="\t", index=False, header=False)

### Analiza asymetrii GC z Wykorzystaniem Okien

W tej sekcji przeprowadzimy analizę asymetrii GC. Tak jak w przypadku zawartości GC przeprowadźmy analizę dla różnych wartości długości okna oraz kroku.

In [58]:
skew_data = {}

for chromname in chromnames:
    seq = fadict[chromname]
    #seq_length = len(seq)
    #print(seq_length)

    skew = sliding_window(seq, w_size, w_step, gc_skew)
    skewdf = pd.DataFrame(skew, columns=["start", "stop", "skew"])
    skew_data[chromname] = skewdf
    print(skewdf)

      start     stop      skew
0         0    50000  0.010524
1     50000   100000  0.005253
2    100000   150000 -0.025394
3    150000   200000  0.024672
4    200000   250000 -0.031651
..      ...      ...       ...
94  4700000  4750000  0.011097
95  4750000  4800000  0.008320
96  4800000  4850000 -0.048026
97  4850000  4900000 -0.002899
98  4900000  4950000 -0.050947

[99 rows x 3 columns]
      start     stop      skew
0         0    50000 -0.025365
1     50000   100000 -0.026361
2    100000   150000  0.002450
3    150000   200000  0.002481
4    200000   250000 -0.008522
5    250000   300000 -0.015273
6    300000   350000  0.006802
7    350000   400000  0.011390
8    400000   450000 -0.005097
9    450000   500000  0.011793
10   500000   550000 -0.020304
11   550000   600000  0.005741
12   600000   650000  0.010304
13   650000   700000  0.006822
14   700000   750000 -0.008808
15   750000   800000  0.025556
16   800000   850000 -0.011348
17   850000   900000 -0.037669
18   900000   950000  0.005389
19   950000  1000000  0.025880
20  1000000  1050000 -0.029950
21  1050000  1100000  0.012791
22  1100000  1150000  0.017551
23  1150000  1200000  0.006667
24  1200000  1250000  0.009122
25  1250000  1300000 -0.007445
26  1300000  1350000 -0.016435
27  1350000  1400000  0.012024
28  1400000  1450000  0.006942
29  1450000  1500000 -0.001392
30  1500000  1550000 -0.002412
31  1550000  1600000 -0.015237
32  1600000  1650000  0.045286
33  1650000  1700000  0.029414
34  1700000  1750000  0.033622
35  1750000  1800000  0.005806
      start     stop      skew
0         0    50000 -0.015225
1     50000   100000 -0.011048
2    100000   150000  0.001069
3    150000   200000 -0.026223
4    200000   250000  0.000081
5    250000   300000  0.022911
6    300000   350000  0.005348
7    350000   400000 -0.019378
8    400000   450000  0.009520
9    450000   500000  0.005338
10   500000   550000  0.034326
11   550000   600000 -0.016203
12   600000   650000 -0.007053
13   650000   700000 -0.003026
14   700000   750000  0.012443
15   750000   800000  0.004911
16   800000   850000  0.006967
17   850000   900000 -0.032151
18   900000   950000 -0.057498
19   950000  1000000 -0.005946
20  1000000  1050000  0.018977
21  1050000  1100000  0.002727
22  1100000  1150000  0.034667
23  1150000  1200000 -0.063350
24  1200000  1250000  0.011413
25  1250000  1300000  0.010720
26  1300000  1350000 -0.007483
27  1350000  1400000 -0.018737
28  1400000  1450000  0.002758
29  1450000  1500000  0.001042
30  1500000  1550000 -0.014292
31  1550000  1600000 -0.004246
32  1600000  1650000 -0.031951
33  1650000  1700000  0.005060
34  1700000  1750000 -0.003266
35  1750000  1800000  0.008376
36  1800000  1850000  0.016544
37  1850000  1900000 -0.036056
38  1900000  1950000 -0.030288
39  1950000  2000000 -0.020582
      start     stop      skew
0         0    50000 -0.010783
1     50000   100000 -0.019570
2    100000   150000  0.006577
3    150000   200000  0.001204
4    200000   250000  0.005728
5    250000   300000 -0.026688
6    300000   350000  0.002609
7    350000   400000  0.016680
8    400000   450000  0.006288
9    450000   500000  0.013814
10   500000   550000  0.003323
11   550000   600000  0.008864
12   600000   650000  0.011978
13   650000   700000 -0.010009
14   700000   750000  0.021261
15   750000   800000  0.014008
16   800000   850000 -0.001107
17   850000   900000  0.008788
18   900000   950000 -0.019193
19   950000  1000000  0.008188
20  1000000  1050000  0.003788
21  1050000  1100000 -0.017297
22  1100000  1150000 -0.014756
23  1150000  1200000  0.001278
24  1200000  1250000  0.002847
25  1250000  1300000  0.022380
26  1300000  1350000  0.011666
27  1350000  1400000  0.009771
28  1400000  1450000 -0.003720
29  1450000  1500000  0.001134
30  1500000  1550000  0.004041
31  1550000  1600000 -0.017246
32  1600000  1650000 -0.001986
33  1650000  1700000  0.011632
34  1700000  1750000  0.015919
35  1750000  1800000 -0.015526
36  1800000  1850000 -0.017923
37  1850000  1900000 -0.004857
38  1900000  1950000 -0.019357
39  1950000  2000000  0.005762
40  2000000  2050000  0.017695
41  2050000  2100000 -0.008897
42  2100000  2150000  0.008505
43  2150000  2200000  0.023927
44  2200000  2250000 -0.025389
45  2250000  2300000 -0.001997
      start     stop      skew
0         0    50000 -0.005010
1     50000   100000 -0.027096
2    100000   150000 -0.019400
3    150000   200000  0.012143
4    200000   250000 -0.003573
5    250000   300000  0.025505
6    300000   350000 -0.019065
7    350000   400000  0.001208
8    400000   450000  0.003219
9    450000   500000  0.019490
10   500000   550000 -0.022781
11   550000   600000 -0.001955
12   600000   650000  0.023334
13   650000   700000  0.016329
14   700000   750000 -0.000331
15   750000   800000  0.015781
16   800000   850000  0.032182
17   850000   900000  0.047246
18   900000   950000 -0.104098
19   950000  1000000 -0.032858
20  1000000  1050000 -0.006640
21  1050000  1100000  0.010480
22  1100000  1150000  0.000598
23  1150000  1200000  0.013489
24  1200000  1250000 -0.007521
25  1250000  1300000  0.001165
26  1300000  1350000 -0.015183
27  1350000  1400000  0.016240
28  1400000  1450000  0.014552
29  1450000  1500000 -0.021027
30  1500000  1550000 -0.010501
31  1550000  1600000  0.002917
32  1600000  1650000 -0.016435
33  1650000  1700000 -0.005844
34  1700000  1750000  0.020416
35  1750000  1800000 -0.016850
36  1800000  1850000  0.001023
37  1850000  1900000 -0.016221
38  1900000  1950000  0.015131
39  1950000  2000000  0.016841
40  2000000  2050000  0.001476
41  2050000  2100000  0.025269
42  2100000  2150000  0.000162
43  2150000  2200000 -0.013777
44  2200000  2250000  0.027147
      start     stop      skew
0         0    50000 -0.020821
1     50000   100000 -0.019590
2    100000   150000  0.031991
3    150000   200000 -0.008140
4    200000   250000 -0.000288
5    250000   300000 -0.008699
6    300000   350000 -0.009415
7    350000   400000 -0.007018
8    400000   450000  0.030090
9    450000   500000 -0.025572
10   500000   550000  0.018525
11   550000   600000  0.004666
12   600000   650000 -0.012703
13   650000   700000  0.000529
14   700000   750000 -0.027023
15   750000   800000 -0.018115
16   800000   850000  0.007845
17   850000   900000 -0.003761
18   900000   950000  0.007273
19   950000  1000000 -0.008428
20  1000000  1050000 -0.003205
21  1050000  1100000 -0.009661
22  1100000  1150000 -0.008132
23  1150000  1200000  0.008782
24  1200000  1250000 -0.021897
25  1250000  1300000 -0.016447
26  1300000  1350000 -0.014580
27  1350000  1400000  0.009526
28  1400000  1450000 -0.008631
29  1450000  1500000  0.001752
30  1500000  1550000 -0.002456
31  1550000  1600000  0.002599
32  1600000  1650000  0.014834
33  1650000  1700000  0.043929
34  1700000  1750000 -0.001427
35  1750000  1800000  0.006938
36  1800000  1850000 -0.010494
37  1850000  1900000 -0.012539
38  1900000  1950000 -0.010925
39  1950000  2000000 -0.005623
40  2000000  2050000 -0.011545
41  2050000  2100000  0.009041
42  2100000  2150000  0.007090
43  2150000  2200000  0.018418
44  2200000  2250000  0.005460
45  2250000  2300000  0.021988
      start     stop      skew
0         0    50000  0.020662
1     50000   100000 -0.061138
2    100000   150000  0.006225
3    150000   200000  0.011075
4    200000   250000 -0.026115
5    250000   300000  0.005756
6    300000   350000 -0.014480
7    350000   400000 -0.008692
8    400000   450000 -0.003086
9    450000   500000  0.014753
10   500000   550000  0.013464
11   550000   600000 -0.016295
12   600000   650000 -0.010849
13   650000   700000 -0.004286
14   700000   750000  0.010673
15   750000   800000 -0.002781
16   800000   850000  0.013853
17   850000   900000  0.008851
18   900000   950000  0.029158
19   950000  1000000  0.001954
20  1000000  1050000  0.004624
21  1050000  1100000 -0.009206
22  1100000  1150000  0.037181
23  1150000  1200000 -0.005419
24  1200000  1250000 -0.008288
25  1250000  1300000  0.017127
26  1300000  1350000 -0.010652
27  1350000  1400000 -0.027796
28  1400000  1450000 -0.031889
29  1450000  1500000 -0.010154
30  1500000  1550000  0.008410
31  1550000  1600000  0.006699
32  1600000  1650000 -0.006514
33  1650000  1700000 -0.022274
34  1700000  1750000  0.044041
35  1750000  1800000 -0.003510
36  1800000  1850000 -0.010440
37  1850000  1900000 -0.000415
38  1900000  1950000 -0.012882
39  1950000  2000000 -0.007280
40  2000000  2050000  0.006896
41  2050000  2100000 -0.022047
42  2100000  2150000 -0.000666
43  2150000  2200000  0.030504
44  2200000  2250000  0.009823
45  2250000  2300000  0.032551
46  2300000  2350000 -0.019986
47  2350000  2400000  0.000613
48  2400000  2450000 -0.030618
49  2450000  2500000 -0.126284
      start     stop      skew
0         0    50000  0.035127
1     50000   100000 -0.080898
2    100000   150000  0.002225
3    150000   200000  0.001202
4    200000   250000 -0.031109
5    250000   300000 -0.022117
6    300000   350000  0.006601
7    350000   400000  0.008133
8    400000   450000  0.009541
9    450000   500000 -0.001133
10   500000   550000  0.009580
11   550000   600000 -0.007311
12   600000   650000  0.020077
13   650000   700000 -0.014998
14   700000   750000 -0.020139
15   750000   800000  0.012704
16   800000   850000 -0.000481
17   850000   900000 -0.026181
18   900000   950000 -0.005969
19   950000  1000000 -0.002211
20  1000000  1050000  0.020702
21  1050000  1100000 -0.006457
22  1100000  1150000 -0.006429
23  1150000  1200000  0.009210
24  1200000  1250000 -0.006743
25  1250000  1300000  0.016356
26  1300000  1350000  0.032392
27  1350000  1400000 -0.022014
28  1400000  1450000  0.001725
29  1450000  1500000 -0.005807
30  1500000  1550000 -0.003965
31  1550000  1600000  0.033609
32  1600000  1650000  0.005079
33  1650000  1700000  0.029856
34  1700000  1750000 -0.032548
35  1750000  1800000 -0.077116
36  1800000  1850000  0.018866
37  1850000  1900000  0.000212
38  1900000  1950000  0.007223
39  1950000  2000000 -0.004982
40  2000000  2050000  0.001036
41  2050000  2100000  0.005883
42  2100000  2150000  0.022198
43  2150000  2200000  0.018884
44  2200000  2250000  0.002428
45  2250000  2300000 -0.016748
46  2300000  2350000  0.020116
47  2350000  2400000  0.002769
48  2400000  2450000 -0.021205
49  2450000  2500000  0.024032
50  2500000  2550000  0.037962
51  2550000  2600000  0.004737
52  2600000  2650000  0.004002
53  2650000  2700000 -0.043739
54  2700000  2750000 -0.019440
55  2750000  2800000  0.036577
      start     stop      skew
0         0    50000  0.006391
1     50000   100000  0.015092
2    100000   150000  0.006172
3    150000   200000  0.012518
4    200000   250000  0.031908
..      ...      ...       ...
57  2850000  2900000  0.013551
58  2900000  2950000  0.008098
59  2950000  3000000 -0.017562
60  3000000  3050000  0.005787
61  3050000  3100000  0.035061

[62 rows x 3 columns]
      start     stop      skew
0         0    50000  0.016420
1     50000   100000 -0.005388
2    100000   150000  0.015633
3    150000   200000  0.005352
4    200000   250000 -0.022909
..      ...      ...       ...
61  3050000  3100000  0.025342
62  3100000  3150000  0.010928
63  3150000  3200000 -0.010964
64  3200000  3250000 -0.024913
65  3250000  3300000 -0.027722

[66 rows x 3 columns]
      start     stop      skew
0         0    50000  0.049457
1     50000   100000 -0.010999
2    100000   150000 -0.063589
3    150000   200000  0.008714
4    200000   250000  0.036506
..      ...      ...       ...
77  3850000  3900000 -0.037300
78  3900000  3950000  0.013111
79  3950000  4000000  0.038676
80  4000000  4050000  0.010259
81  4050000  4100000  0.020576

[82 rows x 3 columns]
      start     stop      skew
0         0    50000  0.005539
1     50000   100000 -0.017074
2    100000   150000  0.007227
3    150000   200000 -0.014320
4    200000   250000 -0.036160
..      ...      ...       ...
69  3450000  3500000 -0.018652
70  3500000  3550000 -0.005765
71  3550000  3600000 -0.010824
72  3600000  3650000 -0.002967
73  3650000  3700000  0.005401

[74 rows x 3 columns]
      start     stop      skew
0         0    50000  0.000000
1     50000   100000 -0.010456
2    100000   150000 -0.002581
3    150000   200000 -0.003627
4    200000   250000  0.033700
..      ...      ...       ...
69  3450000  3500000 -0.004942
70  3500000  3550000  0.010106
71  3550000  3600000  0.015086
72  3600000  3650000  0.008772
73  3650000  3700000  0.003493

[74 rows x 3 columns]
      start     stop      skew
0         0    50000  0.000775
1     50000   100000  0.005545
2    100000   150000  0.005701
3    150000   200000  0.006454
4    200000   250000 -0.015326
..      ...      ...       ...
79  3950000  4000000 -0.005321
80  4000000  4050000 -0.005513
81  4050000  4100000 -0.013405
82  4100000  4150000  0.019562
83  4150000  4200000  0.037021

[84 rows x 3 columns]
      start     stop      skew
0         0    50000 -0.011170
1     50000   100000 -0.012523
2    100000   150000  0.008134
3    150000   200000  0.017235
4    200000   250000 -0.011566
..      ...      ...       ...
80  4000000  4050000  0.001469
81  4050000  4100000  0.019399
82  4100000  4150000 -0.035217
83  4150000  4200000  0.005430
84  4200000  4250000 -0.002649

[85 rows x 3 columns]
      start     stop      skew
0         0    50000  0.094333
1     50000   100000  0.014707
2    100000   150000  0.028607
3    150000   200000 -0.038683
4    200000   250000  0.029512
..      ...      ...       ...
83  4150000  4200000  0.005993
84  4200000  4250000 -0.025513
85  4250000  4300000  0.005174
86  4300000  4350000  0.006042
87  4350000  4400000 -0.023991

[88 rows x 3 columns]

#### Asymetria GC przy pomocy seqkit

In [27]:
!cat {in_fasta}| \
seqkit sliding -s 5000 -W 5000 | \
seqkit fx2tab -n -G|head

NC_000908.2_sliding:1-5000	10.47
NC_000908.2_sliding:5001-10000	11.33
NC_000908.2_sliding:10001-15000	1.80
NC_000908.2_sliding:15001-20000	7.89
NC_000908.2_sliding:20001-25000	11.92
NC_000908.2_sliding:25001-30000	13.15
NC_000908.2_sliding:30001-35000	-3.50
NC_000908.2_sliding:35001-40000	2.37
NC_000908.2_sliding:40001-45000	8.60
NC_000908.2_sliding:45001-50000	2.41

#### Wizualizacja asymetrii GC

Przygotowane dane asymetrii GC zostaną użyte do utworzenia wykresu liniowego.

In [59]:
for chromname, skewdf in skew_data.items():
    skewplot = (ggplot(skewdf, aes(x="start", y="skew")) + geom_line()) + theme_minimal()
    skewplot.save(f"skew_plot_{chromname}", width=8, height=6)

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000007l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000003l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000012l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000008l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000002l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000016l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000018l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000014l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000011l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000015l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000010l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000004l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000001l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000009l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000013l
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_ptg000017l

### Sformatowanie danych do narzędzia Circos

Dane dotyczące zawartości GC zwizualizujemy w postaci wykresu punktowego (scatterplot). Format danych dla tego typu wykresu jest tożsamy z powyższym, rodzaj wykresu określamy w pliku konfiguracyjnym, co zrobimy w dalszej części.


#### Dodawanie Informacji o Chromosomie


W tej sekcji przypiszemy do naszych danych identyfikator chromosomu.

In [60]:
skew_data_insert = deepcopy(skew_data)

for chromname, skewdf in skew_data.items():

    skewdf.insert(0,"chr",chromname)
    skew_data_insert[chromname] = skewdf
    print(skewdf)

           chr    start     stop      skew
0   ptg000007l        0    50000  0.010524
1   ptg000007l    50000   100000  0.005253
2   ptg000007l   100000   150000 -0.025394
3   ptg000007l   150000   200000  0.024672
4   ptg000007l   200000   250000 -0.031651
..         ...      ...      ...       ...
94  ptg000007l  4700000  4750000  0.011097
95  ptg000007l  4750000  4800000  0.008320
96  ptg000007l  4800000  4850000 -0.048026
97  ptg000007l  4850000  4900000 -0.002899
98  ptg000007l  4900000  4950000 -0.050947

[99 rows x 4 columns]
           chr    start     stop      skew
0   ptg000003l        0    50000 -0.025365
1   ptg000003l    50000   100000 -0.026361
2   ptg000003l   100000   150000  0.002450
3   ptg000003l   150000   200000  0.002481
4   ptg000003l   200000   250000 -0.008522
5   ptg000003l   250000   300000 -0.015273
6   ptg000003l   300000   350000  0.006802
7   ptg000003l   350000   400000  0.011390
8   ptg000003l   400000   450000 -0.005097
9   ptg000003l   450000   500000  0.011793
10  ptg000003l   500000   550000 -0.020304
11  ptg000003l   550000   600000  0.005741
12  ptg000003l   600000   650000  0.010304
13  ptg000003l   650000   700000  0.006822
14  ptg000003l   700000   750000 -0.008808
15  ptg000003l   750000   800000  0.025556
16  ptg000003l   800000   850000 -0.011348
17  ptg000003l   850000   900000 -0.037669
18  ptg000003l   900000   950000  0.005389
19  ptg000003l   950000  1000000  0.025880
20  ptg000003l  1000000  1050000 -0.029950
21  ptg000003l  1050000  1100000  0.012791
22  ptg000003l  1100000  1150000  0.017551
23  ptg000003l  1150000  1200000  0.006667
24  ptg000003l  1200000  1250000  0.009122
25  ptg000003l  1250000  1300000 -0.007445
26  ptg000003l  1300000  1350000 -0.016435
27  ptg000003l  1350000  1400000  0.012024
28  ptg000003l  1400000  1450000  0.006942
29  ptg000003l  1450000  1500000 -0.001392
30  ptg000003l  1500000  1550000 -0.002412
31  ptg000003l  1550000  1600000 -0.015237
32  ptg000003l  1600000  1650000  0.045286
33  ptg000003l  1650000  1700000  0.029414
34  ptg000003l  1700000  1750000  0.033622
35  ptg000003l  1750000  1800000  0.005806
           chr    start     stop      skew
0   ptg000012l        0    50000 -0.015225
1   ptg000012l    50000   100000 -0.011048
2   ptg000012l   100000   150000  0.001069
3   ptg000012l   150000   200000 -0.026223
4   ptg000012l   200000   250000  0.000081
5   ptg000012l   250000   300000  0.022911
6   ptg000012l   300000   350000  0.005348
7   ptg000012l   350000   400000 -0.019378
8   ptg000012l   400000   450000  0.009520
9   ptg000012l   450000   500000  0.005338
10  ptg000012l   500000   550000  0.034326
11  ptg000012l   550000   600000 -0.016203
12  ptg000012l   600000   650000 -0.007053
13  ptg000012l   650000   700000 -0.003026
14  ptg000012l   700000   750000  0.012443
15  ptg000012l   750000   800000  0.004911
16  ptg000012l   800000   850000  0.006967
17  ptg000012l   850000   900000 -0.032151
18  ptg000012l   900000   950000 -0.057498
19  ptg000012l   950000  1000000 -0.005946
20  ptg000012l  1000000  1050000  0.018977
21  ptg000012l  1050000  1100000  0.002727
22  ptg000012l  1100000  1150000  0.034667
23  ptg000012l  1150000  1200000 -0.063350
24  ptg000012l  1200000  1250000  0.011413
25  ptg000012l  1250000  1300000  0.010720
26  ptg000012l  1300000  1350000 -0.007483
27  ptg000012l  1350000  1400000 -0.018737
28  ptg000012l  1400000  1450000  0.002758
29  ptg000012l  1450000  1500000  0.001042
30  ptg000012l  1500000  1550000 -0.014292
31  ptg000012l  1550000  1600000 -0.004246
32  ptg000012l  1600000  1650000 -0.031951
33  ptg000012l  1650000  1700000  0.005060
34  ptg000012l  1700000  1750000 -0.003266
35  ptg000012l  1750000  1800000  0.008376
36  ptg000012l  1800000  1850000  0.016544
37  ptg000012l  1850000  1900000 -0.036056
38  ptg000012l  1900000  1950000 -0.030288
39  ptg000012l  1950000  2000000 -0.020582
           chr    start     stop      skew
0   ptg000008l        0    50000 -0.010783
1   ptg000008l    50000   100000 -0.019570
2   ptg000008l   100000   150000  0.006577
3   ptg000008l   150000   200000  0.001204
4   ptg000008l   200000   250000  0.005728
5   ptg000008l   250000   300000 -0.026688
6   ptg000008l   300000   350000  0.002609
7   ptg000008l   350000   400000  0.016680
8   ptg000008l   400000   450000  0.006288
9   ptg000008l   450000   500000  0.013814
10  ptg000008l   500000   550000  0.003323
11  ptg000008l   550000   600000  0.008864
12  ptg000008l   600000   650000  0.011978
13  ptg000008l   650000   700000 -0.010009
14  ptg000008l   700000   750000  0.021261
15  ptg000008l   750000   800000  0.014008
16  ptg000008l   800000   850000 -0.001107
17  ptg000008l   850000   900000  0.008788
18  ptg000008l   900000   950000 -0.019193
19  ptg000008l   950000  1000000  0.008188
20  ptg000008l  1000000  1050000  0.003788
21  ptg000008l  1050000  1100000 -0.017297
22  ptg000008l  1100000  1150000 -0.014756
23  ptg000008l  1150000  1200000  0.001278
24  ptg000008l  1200000  1250000  0.002847
25  ptg000008l  1250000  1300000  0.022380
26  ptg000008l  1300000  1350000  0.011666
27  ptg000008l  1350000  1400000  0.009771
28  ptg000008l  1400000  1450000 -0.003720
29  ptg000008l  1450000  1500000  0.001134
30  ptg000008l  1500000  1550000  0.004041
31  ptg000008l  1550000  1600000 -0.017246
32  ptg000008l  1600000  1650000 -0.001986
33  ptg000008l  1650000  1700000  0.011632
34  ptg000008l  1700000  1750000  0.015919
35  ptg000008l  1750000  1800000 -0.015526
36  ptg000008l  1800000  1850000 -0.017923
37  ptg000008l  1850000  1900000 -0.004857
38  ptg000008l  1900000  1950000 -0.019357
39  ptg000008l  1950000  2000000  0.005762
40  ptg000008l  2000000  2050000  0.017695
41  ptg000008l  2050000  2100000 -0.008897
42  ptg000008l  2100000  2150000  0.008505
43  ptg000008l  2150000  2200000  0.023927
44  ptg000008l  2200000  2250000 -0.025389
45  ptg000008l  2250000  2300000 -0.001997
           chr    start     stop      skew
0   ptg000002l        0    50000 -0.005010
1   ptg000002l    50000   100000 -0.027096
2   ptg000002l   100000   150000 -0.019400
3   ptg000002l   150000   200000  0.012143
4   ptg000002l   200000   250000 -0.003573
5   ptg000002l   250000   300000  0.025505
6   ptg000002l   300000   350000 -0.019065
7   ptg000002l   350000   400000  0.001208
8   ptg000002l   400000   450000  0.003219
9   ptg000002l   450000   500000  0.019490
10  ptg000002l   500000   550000 -0.022781
11  ptg000002l   550000   600000 -0.001955
12  ptg000002l   600000   650000  0.023334
13  ptg000002l   650000   700000  0.016329
14  ptg000002l   700000   750000 -0.000331
15  ptg000002l   750000   800000  0.015781
16  ptg000002l   800000   850000  0.032182
17  ptg000002l   850000   900000  0.047246
18  ptg000002l   900000   950000 -0.104098
19  ptg000002l   950000  1000000 -0.032858
20  ptg000002l  1000000  1050000 -0.006640
21  ptg000002l  1050000  1100000  0.010480
22  ptg000002l  1100000  1150000  0.000598
23  ptg000002l  1150000  1200000  0.013489
24  ptg000002l  1200000  1250000 -0.007521
25  ptg000002l  1250000  1300000  0.001165
26  ptg000002l  1300000  1350000 -0.015183
27  ptg000002l  1350000  1400000  0.016240
28  ptg000002l  1400000  1450000  0.014552
29  ptg000002l  1450000  1500000 -0.021027
30  ptg000002l  1500000  1550000 -0.010501
31  ptg000002l  1550000  1600000  0.002917
32  ptg000002l  1600000  1650000 -0.016435
33  ptg000002l  1650000  1700000 -0.005844
34  ptg000002l  1700000  1750000  0.020416
35  ptg000002l  1750000  1800000 -0.016850
36  ptg000002l  1800000  1850000  0.001023
37  ptg000002l  1850000  1900000 -0.016221
38  ptg000002l  1900000  1950000  0.015131
39  ptg000002l  1950000  2000000  0.016841
40  ptg000002l  2000000  2050000  0.001476
41  ptg000002l  2050000  2100000  0.025269
42  ptg000002l  2100000  2150000  0.000162
43  ptg000002l  2150000  2200000 -0.013777
44  ptg000002l  2200000  2250000  0.027147
           chr    start     stop      skew
0   ptg000016l        0    50000 -0.020821
1   ptg000016l    50000   100000 -0.019590
2   ptg000016l   100000   150000  0.031991
3   ptg000016l   150000   200000 -0.008140
4   ptg000016l   200000   250000 -0.000288
5   ptg000016l   250000   300000 -0.008699
6   ptg000016l   300000   350000 -0.009415
7   ptg000016l   350000   400000 -0.007018
8   ptg000016l   400000   450000  0.030090
9   ptg000016l   450000   500000 -0.025572
10  ptg000016l   500000   550000  0.018525
11  ptg000016l   550000   600000  0.004666
12  ptg000016l   600000   650000 -0.012703
13  ptg000016l   650000   700000  0.000529
14  ptg000016l   700000   750000 -0.027023
15  ptg000016l   750000   800000 -0.018115
16  ptg000016l   800000   850000  0.007845
17  ptg000016l   850000   900000 -0.003761
18  ptg000016l   900000   950000  0.007273
19  ptg000016l   950000  1000000 -0.008428
20  ptg000016l  1000000  1050000 -0.003205
21  ptg000016l  1050000  1100000 -0.009661
22  ptg000016l  1100000  1150000 -0.008132
23  ptg000016l  1150000  1200000  0.008782
24  ptg000016l  1200000  1250000 -0.021897
25  ptg000016l  1250000  1300000 -0.016447
26  ptg000016l  1300000  1350000 -0.014580
27  ptg000016l  1350000  1400000  0.009526
28  ptg000016l  1400000  1450000 -0.008631
29  ptg000016l  1450000  1500000  0.001752
30  ptg000016l  1500000  1550000 -0.002456
31  ptg000016l  1550000  1600000  0.002599
32  ptg000016l  1600000  1650000  0.014834
33  ptg000016l  1650000  1700000  0.043929
34  ptg000016l  1700000  1750000 -0.001427
35  ptg000016l  1750000  1800000  0.006938
36  ptg000016l  1800000  1850000 -0.010494
37  ptg000016l  1850000  1900000 -0.012539
38  ptg000016l  1900000  1950000 -0.010925
39  ptg000016l  1950000  2000000 -0.005623
40  ptg000016l  2000000  2050000 -0.011545
41  ptg000016l  2050000  2100000  0.009041
42  ptg000016l  2100000  2150000  0.007090
43  ptg000016l  2150000  2200000  0.018418
44  ptg000016l  2200000  2250000  0.005460
45  ptg000016l  2250000  2300000  0.021988
           chr    start     stop      skew
0   ptg000018l        0    50000  0.020662
1   ptg000018l    50000   100000 -0.061138
2   ptg000018l   100000   150000  0.006225
3   ptg000018l   150000   200000  0.011075
4   ptg000018l   200000   250000 -0.026115
5   ptg000018l   250000   300000  0.005756
6   ptg000018l   300000   350000 -0.014480
7   ptg000018l   350000   400000 -0.008692
8   ptg000018l   400000   450000 -0.003086
9   ptg000018l   450000   500000  0.014753
10  ptg000018l   500000   550000  0.013464
11  ptg000018l   550000   600000 -0.016295
12  ptg000018l   600000   650000 -0.010849
13  ptg000018l   650000   700000 -0.004286
14  ptg000018l   700000   750000  0.010673
15  ptg000018l   750000   800000 -0.002781
16  ptg000018l   800000   850000  0.013853
17  ptg000018l   850000   900000  0.008851
18  ptg000018l   900000   950000  0.029158
19  ptg000018l   950000  1000000  0.001954
20  ptg000018l  1000000  1050000  0.004624
21  ptg000018l  1050000  1100000 -0.009206
22  ptg000018l  1100000  1150000  0.037181
23  ptg000018l  1150000  1200000 -0.005419
24  ptg000018l  1200000  1250000 -0.008288
25  ptg000018l  1250000  1300000  0.017127
26  ptg000018l  1300000  1350000 -0.010652
27  ptg000018l  1350000  1400000 -0.027796
28  ptg000018l  1400000  1450000 -0.031889
29  ptg000018l  1450000  1500000 -0.010154
30  ptg000018l  1500000  1550000  0.008410
31  ptg000018l  1550000  1600000  0.006699
32  ptg000018l  1600000  1650000 -0.006514
33  ptg000018l  1650000  1700000 -0.022274
34  ptg000018l  1700000  1750000  0.044041
35  ptg000018l  1750000  1800000 -0.003510
36  ptg000018l  1800000  1850000 -0.010440
37  ptg000018l  1850000  1900000 -0.000415
38  ptg000018l  1900000  1950000 -0.012882
39  ptg000018l  1950000  2000000 -0.007280
40  ptg000018l  2000000  2050000  0.006896
41  ptg000018l  2050000  2100000 -0.022047
42  ptg000018l  2100000  2150000 -0.000666
43  ptg000018l  2150000  2200000  0.030504
44  ptg000018l  2200000  2250000  0.009823
45  ptg000018l  2250000  2300000  0.032551
46  ptg000018l  2300000  2350000 -0.019986
47  ptg000018l  2350000  2400000  0.000613
48  ptg000018l  2400000  2450000 -0.030618
49  ptg000018l  2450000  2500000 -0.126284
           chr    start     stop      skew
0   ptg000014l        0    50000  0.035127
1   ptg000014l    50000   100000 -0.080898
2   ptg000014l   100000   150000  0.002225
3   ptg000014l   150000   200000  0.001202
4   ptg000014l   200000   250000 -0.031109
5   ptg000014l   250000   300000 -0.022117
6   ptg000014l   300000   350000  0.006601
7   ptg000014l   350000   400000  0.008133
8   ptg000014l   400000   450000  0.009541
9   ptg000014l   450000   500000 -0.001133
10  ptg000014l   500000   550000  0.009580
11  ptg000014l   550000   600000 -0.007311
12  ptg000014l   600000   650000  0.020077
13  ptg000014l   650000   700000 -0.014998
14  ptg000014l   700000   750000 -0.020139
15  ptg000014l   750000   800000  0.012704
16  ptg000014l   800000   850000 -0.000481
17  ptg000014l   850000   900000 -0.026181
18  ptg000014l   900000   950000 -0.005969
19  ptg000014l   950000  1000000 -0.002211
20  ptg000014l  1000000  1050000  0.020702
21  ptg000014l  1050000  1100000 -0.006457
22  ptg000014l  1100000  1150000 -0.006429
23  ptg000014l  1150000  1200000  0.009210
24  ptg000014l  1200000  1250000 -0.006743
25  ptg000014l  1250000  1300000  0.016356
26  ptg000014l  1300000  1350000  0.032392
27  ptg000014l  1350000  1400000 -0.022014
28  ptg000014l  1400000  1450000  0.001725
29  ptg000014l  1450000  1500000 -0.005807
30  ptg000014l  1500000  1550000 -0.003965
31  ptg000014l  1550000  1600000  0.033609
32  ptg000014l  1600000  1650000  0.005079
33  ptg000014l  1650000  1700000  0.029856
34  ptg000014l  1700000  1750000 -0.032548
35  ptg000014l  1750000  1800000 -0.077116
36  ptg000014l  1800000  1850000  0.018866
37  ptg000014l  1850000  1900000  0.000212
38  ptg000014l  1900000  1950000  0.007223
39  ptg000014l  1950000  2000000 -0.004982
40  ptg000014l  2000000  2050000  0.001036
41  ptg000014l  2050000  2100000  0.005883
42  ptg000014l  2100000  2150000  0.022198
43  ptg000014l  2150000  2200000  0.018884
44  ptg000014l  2200000  2250000  0.002428
45  ptg000014l  2250000  2300000 -0.016748
46  ptg000014l  2300000  2350000  0.020116
47  ptg000014l  2350000  2400000  0.002769
48  ptg000014l  2400000  2450000 -0.021205
49  ptg000014l  2450000  2500000  0.024032
50  ptg000014l  2500000  2550000  0.037962
51  ptg000014l  2550000  2600000  0.004737
52  ptg000014l  2600000  2650000  0.004002
53  ptg000014l  2650000  2700000 -0.043739
54  ptg000014l  2700000  2750000 -0.019440
55  ptg000014l  2750000  2800000  0.036577
           chr    start     stop      skew
0   ptg000011l        0    50000  0.006391
1   ptg000011l    50000   100000  0.015092
2   ptg000011l   100000   150000  0.006172
3   ptg000011l   150000   200000  0.012518
4   ptg000011l   200000   250000  0.031908
..         ...      ...      ...       ...
57  ptg000011l  2850000  2900000  0.013551
58  ptg000011l  2900000  2950000  0.008098
59  ptg000011l  2950000  3000000 -0.017562
60  ptg000011l  3000000  3050000  0.005787
61  ptg000011l  3050000  3100000  0.035061

[62 rows x 4 columns]
           chr    start     stop      skew
0   ptg000015l        0    50000  0.016420
1   ptg000015l    50000   100000 -0.005388
2   ptg000015l   100000   150000  0.015633
3   ptg000015l   150000   200000  0.005352
4   ptg000015l   200000   250000 -0.022909
..         ...      ...      ...       ...
61  ptg000015l  3050000  3100000  0.025342
62  ptg000015l  3100000  3150000  0.010928
63  ptg000015l  3150000  3200000 -0.010964
64  ptg000015l  3200000  3250000 -0.024913
65  ptg000015l  3250000  3300000 -0.027722

[66 rows x 4 columns]
           chr    start     stop      skew
0   ptg000010l        0    50000  0.049457
1   ptg000010l    50000   100000 -0.010999
2   ptg000010l   100000   150000 -0.063589
3   ptg000010l   150000   200000  0.008714
4   ptg000010l   200000   250000  0.036506
..         ...      ...      ...       ...
77  ptg000010l  3850000  3900000 -0.037300
78  ptg000010l  3900000  3950000  0.013111
79  ptg000010l  3950000  4000000  0.038676
80  ptg000010l  4000000  4050000  0.010259
81  ptg000010l  4050000  4100000  0.020576

[82 rows x 4 columns]
           chr    start     stop      skew
0   ptg000004l        0    50000  0.005539
1   ptg000004l    50000   100000 -0.017074
2   ptg000004l   100000   150000  0.007227
3   ptg000004l   150000   200000 -0.014320
4   ptg000004l   200000   250000 -0.036160
..         ...      ...      ...       ...
69  ptg000004l  3450000  3500000 -0.018652
70  ptg000004l  3500000  3550000 -0.005765
71  ptg000004l  3550000  3600000 -0.010824
72  ptg000004l  3600000  3650000 -0.002967
73  ptg000004l  3650000  3700000  0.005401

[74 rows x 4 columns]
           chr    start     stop      skew
0   ptg000001l        0    50000  0.000000
1   ptg000001l    50000   100000 -0.010456
2   ptg000001l   100000   150000 -0.002581
3   ptg000001l   150000   200000 -0.003627
4   ptg000001l   200000   250000  0.033700
..         ...      ...      ...       ...
69  ptg000001l  3450000  3500000 -0.004942
70  ptg000001l  3500000  3550000  0.010106
71  ptg000001l  3550000  3600000  0.015086
72  ptg000001l  3600000  3650000  0.008772
73  ptg000001l  3650000  3700000  0.003493

[74 rows x 4 columns]
           chr    start     stop      skew
0   ptg000009l        0    50000  0.000775
1   ptg000009l    50000   100000  0.005545
2   ptg000009l   100000   150000  0.005701
3   ptg000009l   150000   200000  0.006454
4   ptg000009l   200000   250000 -0.015326
..         ...      ...      ...       ...
79  ptg000009l  3950000  4000000 -0.005321
80  ptg000009l  4000000  4050000 -0.005513
81  ptg000009l  4050000  4100000 -0.013405
82  ptg000009l  4100000  4150000  0.019562
83  ptg000009l  4150000  4200000  0.037021

[84 rows x 4 columns]
           chr    start     stop      skew
0   ptg000013l        0    50000 -0.011170
1   ptg000013l    50000   100000 -0.012523
2   ptg000013l   100000   150000  0.008134
3   ptg000013l   150000   200000  0.017235
4   ptg000013l   200000   250000 -0.011566
..         ...      ...      ...       ...
80  ptg000013l  4000000  4050000  0.001469
81  ptg000013l  4050000  4100000  0.019399
82  ptg000013l  4100000  4150000 -0.035217
83  ptg000013l  4150000  4200000  0.005430
84  ptg000013l  4200000  4250000 -0.002649

[85 rows x 4 columns]
           chr    start     stop      skew
0   ptg000017l        0    50000  0.094333
1   ptg000017l    50000   100000  0.014707
2   ptg000017l   100000   150000  0.028607
3   ptg000017l   150000   200000 -0.038683
4   ptg000017l   200000   250000  0.029512
..         ...      ...      ...       ...
83  ptg000017l  4150000  4200000  0.005993
84  ptg000017l  4200000  4250000 -0.025513
85  ptg000017l  4250000  4300000  0.005174
86  ptg000017l  4300000  4350000  0.006042
87  ptg000017l  4350000  4400000 -0.023991

[88 rows x 4 columns]

#### Przypisanie Kolorów do asymetrii GC
W tej części przypiszemy kolory do różnych zakresów asymetrii GC. Skorzystamy z domyślnie zdefiniowanych kolorów.

In [61]:
skew_data_final = deepcopy(skew_data_insert)

for chromname, skewdf in skew_data_insert.items():
    skewdf["col"] = "fill_color=blue"
    skewdf.loc[skewdf["skew"]>0, "col"] = "fill_color=red"
    skew_data_final[chromname] = skewdf
    print(skewdf)

           chr    start     stop      skew              col
0   ptg000007l        0    50000  0.010524   fill_color=red
1   ptg000007l    50000   100000  0.005253   fill_color=red
2   ptg000007l   100000   150000 -0.025394  fill_color=blue
3   ptg000007l   150000   200000  0.024672   fill_color=red
4   ptg000007l   200000   250000 -0.031651  fill_color=blue
..         ...      ...      ...       ...              ...
94  ptg000007l  4700000  4750000  0.011097   fill_color=red
95  ptg000007l  4750000  4800000  0.008320   fill_color=red
96  ptg000007l  4800000  4850000 -0.048026  fill_color=blue
97  ptg000007l  4850000  4900000 -0.002899  fill_color=blue
98  ptg000007l  4900000  4950000 -0.050947  fill_color=blue

[99 rows x 5 columns]
           chr    start     stop      skew              col
0   ptg000003l        0    50000 -0.025365  fill_color=blue
1   ptg000003l    50000   100000 -0.026361  fill_color=blue
2   ptg000003l   100000   150000  0.002450   fill_color=red
3   ptg000003l   150000   200000  0.002481   fill_color=red
4   ptg000003l   200000   250000 -0.008522  fill_color=blue
5   ptg000003l   250000   300000 -0.015273  fill_color=blue
6   ptg000003l   300000   350000  0.006802   fill_color=red
7   ptg000003l   350000   400000  0.011390   fill_color=red
8   ptg000003l   400000   450000 -0.005097  fill_color=blue
9   ptg000003l   450000   500000  0.011793   fill_color=red
10  ptg000003l   500000   550000 -0.020304  fill_color=blue
11  ptg000003l   550000   600000  0.005741   fill_color=red
12  ptg000003l   600000   650000  0.010304   fill_color=red
13  ptg000003l   650000   700000  0.006822   fill_color=red
14  ptg000003l   700000   750000 -0.008808  fill_color=blue
15  ptg000003l   750000   800000  0.025556   fill_color=red
16  ptg000003l   800000   850000 -0.011348  fill_color=blue
17  ptg000003l   850000   900000 -0.037669  fill_color=blue
18  ptg000003l   900000   950000  0.005389   fill_color=red
19  ptg000003l   950000  1000000  0.025880   fill_color=red
20  ptg000003l  1000000  1050000 -0.029950  fill_color=blue
21  ptg000003l  1050000  1100000  0.012791   fill_color=red
22  ptg000003l  1100000  1150000  0.017551   fill_color=red
23  ptg000003l  1150000  1200000  0.006667   fill_color=red
24  ptg000003l  1200000  1250000  0.009122   fill_color=red
25  ptg000003l  1250000  1300000 -0.007445  fill_color=blue
26  ptg000003l  1300000  1350000 -0.016435  fill_color=blue
27  ptg000003l  1350000  1400000  0.012024   fill_color=red
28  ptg000003l  1400000  1450000  0.006942   fill_color=red
29  ptg000003l  1450000  1500000 -0.001392  fill_color=blue
30  ptg000003l  1500000  1550000 -0.002412  fill_color=blue
31  ptg000003l  1550000  1600000 -0.015237  fill_color=blue
32  ptg000003l  1600000  1650000  0.045286   fill_color=red
33  ptg000003l  1650000  1700000  0.029414   fill_color=red
34  ptg000003l  1700000  1750000  0.033622   fill_color=red
35  ptg000003l  1750000  1800000  0.005806   fill_color=red
           chr    start     stop      skew              col
0   ptg000012l        0    50000 -0.015225  fill_color=blue
1   ptg000012l    50000   100000 -0.011048  fill_color=blue
2   ptg000012l   100000   150000  0.001069   fill_color=red
3   ptg000012l   150000   200000 -0.026223  fill_color=blue
4   ptg000012l   200000   250000  0.000081   fill_color=red
5   ptg000012l   250000   300000  0.022911   fill_color=red
6   ptg000012l   300000   350000  0.005348   fill_color=red
7   ptg000012l   350000   400000 -0.019378  fill_color=blue
8   ptg000012l   400000   450000  0.009520   fill_color=red
9   ptg000012l   450000   500000  0.005338   fill_color=red
10  ptg000012l   500000   550000  0.034326   fill_color=red
11  ptg000012l   550000   600000 -0.016203  fill_color=blue
12  ptg000012l   600000   650000 -0.007053  fill_color=blue
13  ptg000012l   650000   700000 -0.003026  fill_color=blue
14  ptg000012l   700000   750000  0.012443   fill_color=red
15  ptg000012l   750000   800000  0.004911   fill_color=red
16  ptg000012l   800000   850000  0.006967   fill_color=red
17  ptg000012l   850000   900000 -0.032151  fill_color=blue
18  ptg000012l   900000   950000 -0.057498  fill_color=blue
19  ptg000012l   950000  1000000 -0.005946  fill_color=blue
20  ptg000012l  1000000  1050000  0.018977   fill_color=red
21  ptg000012l  1050000  1100000  0.002727   fill_color=red
22  ptg000012l  1100000  1150000  0.034667   fill_color=red
23  ptg000012l  1150000  1200000 -0.063350  fill_color=blue
24  ptg000012l  1200000  1250000  0.011413   fill_color=red
25  ptg000012l  1250000  1300000  0.010720   fill_color=red
26  ptg000012l  1300000  1350000 -0.007483  fill_color=blue
27  ptg000012l  1350000  1400000 -0.018737  fill_color=blue
28  ptg000012l  1400000  1450000  0.002758   fill_color=red
29  ptg000012l  1450000  1500000  0.001042   fill_color=red
30  ptg000012l  1500000  1550000 -0.014292  fill_color=blue
31  ptg000012l  1550000  1600000 -0.004246  fill_color=blue
32  ptg000012l  1600000  1650000 -0.031951  fill_color=blue
33  ptg000012l  1650000  1700000  0.005060   fill_color=red
34  ptg000012l  1700000  1750000 -0.003266  fill_color=blue
35  ptg000012l  1750000  1800000  0.008376   fill_color=red
36  ptg000012l  1800000  1850000  0.016544   fill_color=red
37  ptg000012l  1850000  1900000 -0.036056  fill_color=blue
38  ptg000012l  1900000  1950000 -0.030288  fill_color=blue
39  ptg000012l  1950000  2000000 -0.020582  fill_color=blue
           chr    start     stop      skew              col
0   ptg000008l        0    50000 -0.010783  fill_color=blue
1   ptg000008l    50000   100000 -0.019570  fill_color=blue
2   ptg000008l   100000   150000  0.006577   fill_color=red
3   ptg000008l   150000   200000  0.001204   fill_color=red
4   ptg000008l   200000   250000  0.005728   fill_color=red
5   ptg000008l   250000   300000 -0.026688  fill_color=blue
6   ptg000008l   300000   350000  0.002609   fill_color=red
7   ptg000008l   350000   400000  0.016680   fill_color=red
8   ptg000008l   400000   450000  0.006288   fill_color=red
9   ptg000008l   450000   500000  0.013814   fill_color=red
10  ptg000008l   500000   550000  0.003323   fill_color=red
11  ptg000008l   550000   600000  0.008864   fill_color=red
12  ptg000008l   600000   650000  0.011978   fill_color=red
13  ptg000008l   650000   700000 -0.010009  fill_color=blue
14  ptg000008l   700000   750000  0.021261   fill_color=red
15  ptg000008l   750000   800000  0.014008   fill_color=red
16  ptg000008l   800000   850000 -0.001107  fill_color=blue
17  ptg000008l   850000   900000  0.008788   fill_color=red
18  ptg000008l   900000   950000 -0.019193  fill_color=blue
19  ptg000008l   950000  1000000  0.008188   fill_color=red
20  ptg000008l  1000000  1050000  0.003788   fill_color=red
21  ptg000008l  1050000  1100000 -0.017297  fill_color=blue
22  ptg000008l  1100000  1150000 -0.014756  fill_color=blue
23  ptg000008l  1150000  1200000  0.001278   fill_color=red
24  ptg000008l  1200000  1250000  0.002847   fill_color=red
25  ptg000008l  1250000  1300000  0.022380   fill_color=red
26  ptg000008l  1300000  1350000  0.011666   fill_color=red
27  ptg000008l  1350000  1400000  0.009771   fill_color=red
28  ptg000008l  1400000  1450000 -0.003720  fill_color=blue
29  ptg000008l  1450000  1500000  0.001134   fill_color=red
30  ptg000008l  1500000  1550000  0.004041   fill_color=red
31  ptg000008l  1550000  1600000 -0.017246  fill_color=blue
32  ptg000008l  1600000  1650000 -0.001986  fill_color=blue
33  ptg000008l  1650000  1700000  0.011632   fill_color=red
34  ptg000008l  1700000  1750000  0.015919   fill_color=red
35  ptg000008l  1750000  1800000 -0.015526  fill_color=blue
36  ptg000008l  1800000  1850000 -0.017923  fill_color=blue
37  ptg000008l  1850000  1900000 -0.004857  fill_color=blue
38  ptg000008l  1900000  1950000 -0.019357  fill_color=blue
39  ptg000008l  1950000  2000000  0.005762   fill_color=red
40  ptg000008l  2000000  2050000  0.017695   fill_color=red
41  ptg000008l  2050000  2100000 -0.008897  fill_color=blue
42  ptg000008l  2100000  2150000  0.008505   fill_color=red
43  ptg000008l  2150000  2200000  0.023927   fill_color=red
44  ptg000008l  2200000  2250000 -0.025389  fill_color=blue
45  ptg000008l  2250000  2300000 -0.001997  fill_color=blue
           chr    start     stop      skew              col
0   ptg000002l        0    50000 -0.005010  fill_color=blue
1   ptg000002l    50000   100000 -0.027096  fill_color=blue
2   ptg000002l   100000   150000 -0.019400  fill_color=blue
3   ptg000002l   150000   200000  0.012143   fill_color=red
4   ptg000002l   200000   250000 -0.003573  fill_color=blue
5   ptg000002l   250000   300000  0.025505   fill_color=red
6   ptg000002l   300000   350000 -0.019065  fill_color=blue
7   ptg000002l   350000   400000  0.001208   fill_color=red
8   ptg000002l   400000   450000  0.003219   fill_color=red
9   ptg000002l   450000   500000  0.019490   fill_color=red
10  ptg000002l   500000   550000 -0.022781  fill_color=blue
11  ptg000002l   550000   600000 -0.001955  fill_color=blue
12  ptg000002l   600000   650000  0.023334   fill_color=red
13  ptg000002l   650000   700000  0.016329   fill_color=red
14  ptg000002l   700000   750000 -0.000331  fill_color=blue
15  ptg000002l   750000   800000  0.015781   fill_color=red
16  ptg000002l   800000   850000  0.032182   fill_color=red
17  ptg000002l   850000   900000  0.047246   fill_color=red
18  ptg000002l   900000   950000 -0.104098  fill_color=blue
19  ptg000002l   950000  1000000 -0.032858  fill_color=blue
20  ptg000002l  1000000  1050000 -0.006640  fill_color=blue
21  ptg000002l  1050000  1100000  0.010480   fill_color=red
22  ptg000002l  1100000  1150000  0.000598   fill_color=red
23  ptg000002l  1150000  1200000  0.013489   fill_color=red
24  ptg000002l  1200000  1250000 -0.007521  fill_color=blue
25  ptg000002l  1250000  1300000  0.001165   fill_color=red
26  ptg000002l  1300000  1350000 -0.015183  fill_color=blue
27  ptg000002l  1350000  1400000  0.016240   fill_color=red
28  ptg000002l  1400000  1450000  0.014552   fill_color=red
29  ptg000002l  1450000  1500000 -0.021027  fill_color=blue
30  ptg000002l  1500000  1550000 -0.010501  fill_color=blue
31  ptg000002l  1550000  1600000  0.002917   fill_color=red
32  ptg000002l  1600000  1650000 -0.016435  fill_color=blue
33  ptg000002l  1650000  1700000 -0.005844  fill_color=blue
34  ptg000002l  1700000  1750000  0.020416   fill_color=red
35  ptg000002l  1750000  1800000 -0.016850  fill_color=blue
36  ptg000002l  1800000  1850000  0.001023   fill_color=red
37  ptg000002l  1850000  1900000 -0.016221  fill_color=blue
38  ptg000002l  1900000  1950000  0.015131   fill_color=red
39  ptg000002l  1950000  2000000  0.016841   fill_color=red
40  ptg000002l  2000000  2050000  0.001476   fill_color=red
41  ptg000002l  2050000  2100000  0.025269   fill_color=red
42  ptg000002l  2100000  2150000  0.000162   fill_color=red
43  ptg000002l  2150000  2200000 -0.013777  fill_color=blue
44  ptg000002l  2200000  2250000  0.027147   fill_color=red
           chr    start     stop      skew              col
0   ptg000016l        0    50000 -0.020821  fill_color=blue
1   ptg000016l    50000   100000 -0.019590  fill_color=blue
2   ptg000016l   100000   150000  0.031991   fill_color=red
3   ptg000016l   150000   200000 -0.008140  fill_color=blue
4   ptg000016l   200000   250000 -0.000288  fill_color=blue
5   ptg000016l   250000   300000 -0.008699  fill_color=blue
6   ptg000016l   300000   350000 -0.009415  fill_color=blue
7   ptg000016l   350000   400000 -0.007018  fill_color=blue
8   ptg000016l   400000   450000  0.030090   fill_color=red
9   ptg000016l   450000   500000 -0.025572  fill_color=blue
10  ptg000016l   500000   550000  0.018525   fill_color=red
11  ptg000016l   550000   600000  0.004666   fill_color=red
12  ptg000016l   600000   650000 -0.012703  fill_color=blue
13  ptg000016l   650000   700000  0.000529   fill_color=red
14  ptg000016l   700000   750000 -0.027023  fill_color=blue
15  ptg000016l   750000   800000 -0.018115  fill_color=blue
16  ptg000016l   800000   850000  0.007845   fill_color=red
17  ptg000016l   850000   900000 -0.003761  fill_color=blue
18  ptg000016l   900000   950000  0.007273   fill_color=red
19  ptg000016l   950000  1000000 -0.008428  fill_color=blue
20  ptg000016l  1000000  1050000 -0.003205  fill_color=blue
21  ptg000016l  1050000  1100000 -0.009661  fill_color=blue
22  ptg000016l  1100000  1150000 -0.008132  fill_color=blue
23  ptg000016l  1150000  1200000  0.008782   fill_color=red
24  ptg000016l  1200000  1250000 -0.021897  fill_color=blue
25  ptg000016l  1250000  1300000 -0.016447  fill_color=blue
26  ptg000016l  1300000  1350000 -0.014580  fill_color=blue
27  ptg000016l  1350000  1400000  0.009526   fill_color=red
28  ptg000016l  1400000  1450000 -0.008631  fill_color=blue
29  ptg000016l  1450000  1500000  0.001752   fill_color=red
30  ptg000016l  1500000  1550000 -0.002456  fill_color=blue
31  ptg000016l  1550000  1600000  0.002599   fill_color=red
32  ptg000016l  1600000  1650000  0.014834   fill_color=red
33  ptg000016l  1650000  1700000  0.043929   fill_color=red
34  ptg000016l  1700000  1750000 -0.001427  fill_color=blue
35  ptg000016l  1750000  1800000  0.006938   fill_color=red
36  ptg000016l  1800000  1850000 -0.010494  fill_color=blue
37  ptg000016l  1850000  1900000 -0.012539  fill_color=blue
38  ptg000016l  1900000  1950000 -0.010925  fill_color=blue
39  ptg000016l  1950000  2000000 -0.005623  fill_color=blue
40  ptg000016l  2000000  2050000 -0.011545  fill_color=blue
41  ptg000016l  2050000  2100000  0.009041   fill_color=red
42  ptg000016l  2100000  2150000  0.007090   fill_color=red
43  ptg000016l  2150000  2200000  0.018418   fill_color=red
44  ptg000016l  2200000  2250000  0.005460   fill_color=red
45  ptg000016l  2250000  2300000  0.021988   fill_color=red
           chr    start     stop      skew              col
0   ptg000018l        0    50000  0.020662   fill_color=red
1   ptg000018l    50000   100000 -0.061138  fill_color=blue
2   ptg000018l   100000   150000  0.006225   fill_color=red
3   ptg000018l   150000   200000  0.011075   fill_color=red
4   ptg000018l   200000   250000 -0.026115  fill_color=blue
5   ptg000018l   250000   300000  0.005756   fill_color=red
6   ptg000018l   300000   350000 -0.014480  fill_color=blue
7   ptg000018l   350000   400000 -0.008692  fill_color=blue
8   ptg000018l   400000   450000 -0.003086  fill_color=blue
9   ptg000018l   450000   500000  0.014753   fill_color=red
10  ptg000018l   500000   550000  0.013464   fill_color=red
11  ptg000018l   550000   600000 -0.016295  fill_color=blue
12  ptg000018l   600000   650000 -0.010849  fill_color=blue
13  ptg000018l   650000   700000 -0.004286  fill_color=blue
14  ptg000018l   700000   750000  0.010673   fill_color=red
15  ptg000018l   750000   800000 -0.002781  fill_color=blue
16  ptg000018l   800000   850000  0.013853   fill_color=red
17  ptg000018l   850000   900000  0.008851   fill_color=red
18  ptg000018l   900000   950000  0.029158   fill_color=red
19  ptg000018l   950000  1000000  0.001954   fill_color=red
20  ptg000018l  1000000  1050000  0.004624   fill_color=red
21  ptg000018l  1050000  1100000 -0.009206  fill_color=blue
22  ptg000018l  1100000  1150000  0.037181   fill_color=red
23  ptg000018l  1150000  1200000 -0.005419  fill_color=blue
24  ptg000018l  1200000  1250000 -0.008288  fill_color=blue
25  ptg000018l  1250000  1300000  0.017127   fill_color=red
26  ptg000018l  1300000  1350000 -0.010652  fill_color=blue
27  ptg000018l  1350000  1400000 -0.027796  fill_color=blue
28  ptg000018l  1400000  1450000 -0.031889  fill_color=blue
29  ptg000018l  1450000  1500000 -0.010154  fill_color=blue
30  ptg000018l  1500000  1550000  0.008410   fill_color=red
31  ptg000018l  1550000  1600000  0.006699   fill_color=red
32  ptg000018l  1600000  1650000 -0.006514  fill_color=blue
33  ptg000018l  1650000  1700000 -0.022274  fill_color=blue
34  ptg000018l  1700000  1750000  0.044041   fill_color=red
35  ptg000018l  1750000  1800000 -0.003510  fill_color=blue
36  ptg000018l  1800000  1850000 -0.010440  fill_color=blue
37  ptg000018l  1850000  1900000 -0.000415  fill_color=blue
38  ptg000018l  1900000  1950000 -0.012882  fill_color=blue
39  ptg000018l  1950000  2000000 -0.007280  fill_color=blue
40  ptg000018l  2000000  2050000  0.006896   fill_color=red
41  ptg000018l  2050000  2100000 -0.022047  fill_color=blue
42  ptg000018l  2100000  2150000 -0.000666  fill_color=blue
43  ptg000018l  2150000  2200000  0.030504   fill_color=red
44  ptg000018l  2200000  2250000  0.009823   fill_color=red
45  ptg000018l  2250000  2300000  0.032551   fill_color=red
46  ptg000018l  2300000  2350000 -0.019986  fill_color=blue
47  ptg000018l  2350000  2400000  0.000613   fill_color=red
48  ptg000018l  2400000  2450000 -0.030618  fill_color=blue
49  ptg000018l  2450000  2500000 -0.126284  fill_color=blue
           chr    start     stop      skew              col
0   ptg000014l        0    50000  0.035127   fill_color=red
1   ptg000014l    50000   100000 -0.080898  fill_color=blue
2   ptg000014l   100000   150000  0.002225   fill_color=red
3   ptg000014l   150000   200000  0.001202   fill_color=red
4   ptg000014l   200000   250000 -0.031109  fill_color=blue
5   ptg000014l   250000   300000 -0.022117  fill_color=blue
6   ptg000014l   300000   350000  0.006601   fill_color=red
7   ptg000014l   350000   400000  0.008133   fill_color=red
8   ptg000014l   400000   450000  0.009541   fill_color=red
9   ptg000014l   450000   500000 -0.001133  fill_color=blue
10  ptg000014l   500000   550000  0.009580   fill_color=red
11  ptg000014l   550000   600000 -0.007311  fill_color=blue
12  ptg000014l   600000   650000  0.020077   fill_color=red
13  ptg000014l   650000   700000 -0.014998  fill_color=blue
14  ptg000014l   700000   750000 -0.020139  fill_color=blue
15  ptg000014l   750000   800000  0.012704   fill_color=red
16  ptg000014l   800000   850000 -0.000481  fill_color=blue
17  ptg000014l   850000   900000 -0.026181  fill_color=blue
18  ptg000014l   900000   950000 -0.005969  fill_color=blue
19  ptg000014l   950000  1000000 -0.002211  fill_color=blue
20  ptg000014l  1000000  1050000  0.020702   fill_color=red
21  ptg000014l  1050000  1100000 -0.006457  fill_color=blue
22  ptg000014l  1100000  1150000 -0.006429  fill_color=blue
23  ptg000014l  1150000  1200000  0.009210   fill_color=red
24  ptg000014l  1200000  1250000 -0.006743  fill_color=blue
25  ptg000014l  1250000  1300000  0.016356   fill_color=red
26  ptg000014l  1300000  1350000  0.032392   fill_color=red
27  ptg000014l  1350000  1400000 -0.022014  fill_color=blue
28  ptg000014l  1400000  1450000  0.001725   fill_color=red
29  ptg000014l  1450000  1500000 -0.005807  fill_color=blue
30  ptg000014l  1500000  1550000 -0.003965  fill_color=blue
31  ptg000014l  1550000  1600000  0.033609   fill_color=red
32  ptg000014l  1600000  1650000  0.005079   fill_color=red
33  ptg000014l  1650000  1700000  0.029856   fill_color=red
34  ptg000014l  1700000  1750000 -0.032548  fill_color=blue
35  ptg000014l  1750000  1800000 -0.077116  fill_color=blue
36  ptg000014l  1800000  1850000  0.018866   fill_color=red
37  ptg000014l  1850000  1900000  0.000212   fill_color=red
38  ptg000014l  1900000  1950000  0.007223   fill_color=red
39  ptg000014l  1950000  2000000 -0.004982  fill_color=blue
40  ptg000014l  2000000  2050000  0.001036   fill_color=red
41  ptg000014l  2050000  2100000  0.005883   fill_color=red
42  ptg000014l  2100000  2150000  0.022198   fill_color=red
43  ptg000014l  2150000  2200000  0.018884   fill_color=red
44  ptg000014l  2200000  2250000  0.002428   fill_color=red
45  ptg000014l  2250000  2300000 -0.016748  fill_color=blue
46  ptg000014l  2300000  2350000  0.020116   fill_color=red
47  ptg000014l  2350000  2400000  0.002769   fill_color=red
48  ptg000014l  2400000  2450000 -0.021205  fill_color=blue
49  ptg000014l  2450000  2500000  0.024032   fill_color=red

#### Zapisywanie danych

In [46]:
for chromname, skewdf in skew_data_final.items():
    skewdf.to_csv(f"gc_skew_{chromname}.histo", sep="\t", index=False, header=False)

### Obliczanie Kumulatywnej Asymetrii GC

Kumulatywna asymetria GC to kumulatywna suma skosu GC kolejnych oknach. W tej sekcji obliczymy i przeskalujemy te wartości, aby uzyskać wyniki w określonym zakresie, co ułatwi nam zwizualizowanie asymetrii GC i kumulatywnej asymetrii GC na jednym wykresie.

In [62]:
skew_data_cuml = deepcopy(skew_data_final)

for chromname, skewdf in skew_data_final.items():
    skew_cuml = []
    cumul = 0

    # Dla każdego okna dodajemy skew poprzedniego okna
    for idx in range(skewdf.shape[0]):
        cumul += skewdf.iloc[idx,]["skew"]
        skew_cuml.append(cumul)
    
    skew_cuml = np.array(skew_cuml)
    skew_data_cuml[chromname] = [skewdf, skew_cuml]

#### Przeskalowanie wartości kumulatywnej asymetrii GC do zakresu 0-1

In [64]:
skew_data_cuml_scaled = deepcopy(skew_data_cuml)

for chromname, skew_df_cuml in skew_data_cuml.items():
    skewdf = skew_df_cuml[0]
    skew_cuml = skew_df_cuml[1]

    skew_cuml_scaled = rescale_range(skew_cuml, min(skew_cuml), max(skew_cuml))
    print(skew_cuml_scaled)
    skew_data_cuml_scaled[chromname] = [skewdf, skew_cuml_scaled]

[0.2035306  0.23105314 0.09799366 0.22727015 0.06142769 0.0461883
 0.16006133 0.2511428  0.49011882 0.59955219 0.62365127 0.6479537
 0.71094061 0.92925308 1.         0.8748154  0.61519081 0.56603755
 0.47855801 0.17290482 0.09097155 0.20070896 0.30943473 0.46078766
 0.32052787 0.38919357 0.45165578 0.38336614 0.44844813 0.42633584
 0.44865611 0.39520239 0.26701959 0.32341641 0.29551002 0.3369777
 0.27745688 0.33547334 0.29955163 0.38753076 0.37618621 0.39174054
 0.3652626  0.35056517 0.41250658 0.43179654 0.23039243 0.22997092
 0.17109272 0.23002659 0.16219014 0.22280006 0.25077955 0.24293848
 0.15283247 0.14321527 0.04686691 0.14982198 0.05302698 0.04930616
 0.06094767 0.05217304 0.05281836 0.11160281 0.14457855 0.15245721
 0.         0.07435391 0.17456918 0.18061704 0.23871749 0.25287609
 0.31905154 0.295224   0.35214606 0.37241073 0.3436521  0.41032913
 0.38160963 0.34603192 0.32997804 0.38682213 0.35540858 0.41053211
 0.44652307 0.37930304 0.40402403 0.29628165 0.40631977 0.39880102
 0.32285671 0.439008   0.57685078 0.56013204 0.61827601 0.6618725
 0.4102291  0.39503894 0.1280918 ]
[0.36363093 0.1720849  0.18988491 0.2079122  0.14598762 0.03501179
 0.08443379 0.16719253 0.13015778 0.21584577 0.06831562 0.11002959
 0.18490328 0.23447301 0.17047261 0.3561681  0.27371114 0.
 0.03915591 0.2272044  0.00957895 0.10252253 0.2300533  0.27849869
 0.34478118 0.29068726 0.1712685  0.25863846 0.30908057 0.29896519
 0.28144141 0.17072553 0.49978077 0.71351092 0.95781278 1.        ]
[0.89818378 0.84692054 0.85187962 0.73020636 0.73058225 0.83688823
 0.86170261 0.77179065 0.81596274 0.84073095 1.         0.92482025
 0.89209287 0.87805208 0.93578509 0.9585707  0.99089689 0.84171834
 0.57493389 0.54734596 0.63539659 0.64804895 0.80890024 0.51496289
 0.56791828 0.61765924 0.58293672 0.49599958 0.50879725 0.51363351
 0.44732186 0.42762109 0.2793735  0.3028521  0.28770013 0.32656624
 0.40333019 0.23603481 0.09549988 0.        ]
[0.28491075 0.11465785 0.17187413 0.18235026 0.23218272 0.
 0.0226993  0.16781088 0.22251809 0.34270259 0.37160819 0.4487253
 0.55293678 0.46585938 0.65082816 0.77269927 0.76306721 0.8395237
 0.67254894 0.74378058 0.7767376  0.62625158 0.4978756  0.50899456
 0.53376267 0.72846806 0.82995964 0.91496789 0.8826082  0.89247077
 0.92762398 0.77758863 0.76030945 0.86150888 1.         0.86492291
 0.70899781 0.66674294 0.49833522 0.54846148 0.70240531 0.62500278
 0.69899761 0.90715737 0.68627454 0.6689018 ]
[0.40662622 0.24936433 0.13676844 0.20724745 0.18651218 0.33453953
 0.22388893 0.23089999 0.24958092 0.36270131 0.23048101 0.21913338
 0.35456038 0.44933384 0.4474155  0.53900542 0.72578715 1.
 0.39582246 0.20511412 0.16657468 0.22739798 0.23086855 0.30915746
 0.26550818 0.27227242 0.18414907 0.27840723 0.36286611 0.24082875
 0.17988435 0.19681615 0.1014271  0.06750923 0.186005   0.08821059
 0.09414728 0.         0.08782031 0.18556499 0.1941317  0.34079325
 0.34173637 0.26177411 0.41933119]
[0.90108061 0.74483098 1.         0.9350735  0.93277536 0.86338955
 0.78829533 0.73231879 0.97232031 0.7683536  0.91611414 0.95333105
 0.85200612 0.85622786 0.64069091 0.49619975 0.55876916 0.52876812
 0.58678247 0.51956028 0.49399972 0.4169399  0.35207731 0.42212265
 0.24747199 0.1162915  0.         0.07598163 0.0071424  0.02111915
 0.00152641 0.02225534 0.14057095 0.49095395 0.47957387 0.53491033
 0.45121038 0.35119467 0.26405753 0.21920528 0.12712157 0.19923081
 0.25578516 0.4026869  0.44624033 0.62162317]
[0.98008369 0.68019653 0.71073086 0.76505547 0.63696099 0.66519473
 0.59417028 0.55153493 0.53640017 0.60876625 0.67480867 0.59488287
 0.5416664  0.52064207 0.57299379 0.55935265 0.62730313 0.67071787
 0.81373803 0.82332475 0.84600396 0.80084815 0.98322401 0.95664259
 0.91598997 1.         0.94775181 0.81140811 0.65499014 0.60518214
 0.6464346  0.67929272 0.64734049 0.53808599 0.75411154 0.73689506
 0.68568711 0.68365097 0.62046191 0.58475376 0.6185792  0.51043487
 0.50716845 0.65679475 0.70497821 0.8646426  0.76661095 0.76961738
 0.61943259 0.        ]
[1.         0.47683078 0.49121823 0.49899141 0.29781178 0.15478047
 0.19746882 0.25006749 0.3117668  0.30443754 0.36639288 0.31911468
 0.44895489 0.35196549 0.22172905 0.30388911 0.30078071 0.13146677
 0.09286786 0.07856777 0.21244708 0.1706909  0.12911512 0.18867667
 0.14507191 0.25084768 0.46032917 0.31796741 0.32912202 0.29156862
 0.26592453 0.48327256 0.51612125 0.70919901 0.49871032 0.
 0.12200944 0.12337986 0.17009167 0.13787322 0.14456999 0.18261281
 0.32616487 0.44828563 0.4639899  0.35568158 0.48577059 0.50367726
 0.36654698 0.52196269 0.7674609  0.79809754 0.82397913 0.54112029
 0.41540442 0.65194906]
[0.         0.05669057 0.07987314 0.12689695 0.24675344 0.23192037
 0.2357645  0.20560375 0.14236865 0.12180878 0.13487239 0.18084648
 0.21746419 0.21437965 0.26330694 0.22044109 0.21588374 0.28939545
 0.21125436 0.24683552 0.19970394 0.21078095 0.19911671 0.32058876
 0.37047168 0.30539772 0.23879145 0.22712767 0.26748531 0.36740926
 0.34236178 0.27034289 0.18806884 0.25576053 0.15485544 0.14116499
 0.05682384 0.15838832 0.19689678 0.22334452 0.2513593  0.28212049
 0.26922273 0.33010415 0.54744348 0.52953373 0.49942828 0.56154712
 0.53931647 0.53162245 0.64487479 0.67898805 0.77869525 0.75785361
 0.84264353 0.76475541 0.83121236 0.88211488 0.91253264 0.84656362
 0.86829998 1.        ]
[0.951564   0.93483223 0.98337929 1.         0.92885625 0.81176883
 0.7788789  0.65565606 0.64378591 0.56527401 0.59267857 0.48920794
 0.3907679  0.37403232 0.32540525 0.23623657 0.12445541 0.0478464
 0.         0.00519929 0.04110961 0.02255587 0.08404834 0.07636086
 0.12188593 0.29933169 0.356924   0.50729481 0.51036132 0.52123237
 0.5407913  0.63185285 0.59870947 0.56415967 0.53799271 0.55361638
 0.62544075 0.56754705 0.6099757  0.53764294 0.56236077 0.62180658
 0.65315951 0.69849521 0.56407941 0.64662574 0.66902332 0.65780178
 0.71466187 0.63821023 0.57498269 0.60474869 0.61111731 0.74647481
 0.85716194 0.80843312 0.82298363 0.78249226 0.69749757 0.7284773
 0.81558281 0.89428201 0.92821827 0.89416877 0.81680302 0.73071318]
[0.69556425 0.64699376 0.36617902 0.40466069 0.56587347 0.36834634
 0.14664641 0.         0.06439509 0.37186908 0.28539636 0.26756462
 0.19068533 0.32062197 0.28556507 0.32814317 0.4085117  0.52027907
 0.50904867 0.40942702 0.309186   0.30595077 0.34474048 0.38901335
 0.38125841 0.4255741  0.42749315 0.51686015 0.5821716  0.54612481
 0.55019754 0.5476606  0.52425626 0.5629708  0.58996808 0.66028177
 0.6168472  0.64286191 0.66697582 0.55122636 0.64946349 0.59512195
 0.47190798 0.53113745 0.60433224 0.65176293 0.6161622  0.71271561
 0.61900096 0.5229914  0.4874247  0.51340786 0.62268661 0.57250182
 0.58909038 0.58644928 0.63276691 0.63942556 0.6853047  0.66489895
 0.65728349 0.56194656 0.63828004 0.64490837 0.62586805 0.59604178
 0.67071795 0.70299902 0.62093126 0.53630867 0.54965031 0.56235821
 0.54931841 0.60393708 0.615866   0.68963618 0.79984959 0.63513147
 0.69302921 0.86382744 0.90913405 1.        ]
[0.35965298 0.29429503 0.32195861 0.26714334 0.12872776 0.11817272
 0.07577502 0.11425934 0.11645047 0.08870739 0.10237508 0.08271899
 0.07160243 0.15336981 0.20501104 0.23988693 0.19866527 0.19726453
 0.15864297 0.         0.06274724 0.09358267 0.07193417 0.19556744
 0.21833002 0.15886106 0.19500491 0.24516034 0.20857305 0.18604102
 0.23233551 0.27647343 0.32252773 0.31847068 0.35504602 0.42199323
 0.45971195 0.41932628 0.40016698 0.48565525 0.53157311 0.4713796
 0.39011409 0.33038658 0.38343562 0.41130762 0.34653684 0.30435394
 0.33039618 0.51043824 0.70914307 0.63648424 0.64779154 0.61357015
 0.65465198 0.64167807 0.58494635 0.57095652 0.61109809 0.71069048
 0.77278117 0.67616566 0.69656071 0.79244785 0.91821861 1.
 0.97115164 0.87010676 0.87219966 0.8007998  0.77873233 0.73729997
 0.7259412  0.74661499]
[0.22514955 0.17754006 0.16578911 0.14927548 0.30272601 0.1681719
 0.31479756 0.17818886 0.12516505 0.06901421 0.151438   0.18953383
 0.18972206 0.12231339 0.18110485 0.15753295 0.2738859  0.33640831
 0.30846126 0.28444749 0.28885255 0.39691186 0.31610774 0.32833536
 0.29401723 0.2994954  0.16939558 0.11641717 0.13129909 0.3337201
 0.27998772 0.26846371 0.25814251 0.26438671 0.13210413 0.
 0.15723416 0.05596927 0.05981773 0.11268456 0.21624981 0.35195324
 0.45121952 0.46685678 0.53700839 0.49977298 0.45119773 0.46074624
 0.61277447 0.72780192 0.8198113  0.79890557 0.74298179 0.7167533
 0.77580138 0.85354051 0.81783405 0.8320366  0.80383981 0.85567435
 1.         0.91781379 0.88115607 0.90492189 0.92550996 0.9937472
 0.95078599 0.76930271 0.85169177 0.82918876 0.87520623 0.94389999
 0.98384292 0.99974966]
[0.03707709 0.07276073 0.10944581 0.15097779 0.05236053 0.07417887
 0.23719355 0.24551797 0.13607504 0.15732733 0.15732733 0.13251621
 0.08078331 0.06430501 0.06146017 0.25547865 0.22738607 0.36677996
 0.37635359 0.41894082 0.50330555 0.4858843  0.59311813 0.58758296
 0.69234353 0.63945922 0.62738175 0.69411199 0.73855747 0.89340778
 1.         0.92488189 0.87594223 0.83197356 0.89290844 0.95775146
 0.99540926 0.97742441 0.93490996 0.98754512 0.86011882 0.63650682
 0.60943636 0.64154034 0.59206743 0.63078873 0.53740257 0.36896939
 0.28984797 0.09545852 0.2308808  0.49869719 0.66512508 0.72520899
 0.55865691 0.51049947 0.85789479 0.72327099 0.83736076 0.55542757
 0.65204583 0.65204583 0.74564257 0.64787807 0.46527099 0.45207837
 0.38258947 0.40729468 0.37567881 0.27853382 0.22070276 0.1984575
 0.03279584 0.16043036 0.08080518 0.17683845 0.         0.17299666
 0.42157096 0.38733186 0.35185717 0.26559712 0.39147498 0.62969634]
[0.43583561 0.37894703 0.41589817 0.49419039 0.441651   0.49956872
 0.51536935 0.63717474 0.63921456 0.68550798 0.73644255 0.71117821
 0.63018975 0.54717971 0.5123637  0.54751539 0.52972857 0.52646436
 0.48762527 0.33144037 0.30185793 0.24898017 0.08399928 0.04825612
 0.02374125 0.02222297 0.02087334 0.07155613 0.         0.12692842
 0.14382547 0.16516667 0.12572227 0.12890355 0.26344449 0.42395253
 0.49082376 0.56523931 0.56562175 0.52521866 0.69780099 0.64037264
 0.67493109 0.748785   0.67818309 0.73603572 0.77014401 0.77417716
 0.79888454 0.66654906 0.73214864 0.62257555 0.57772848 0.57642445
 0.56278713 0.58109385 0.61259699 0.71556936 0.71958524 0.70651068
 0.66321875 0.90104758 1.         0.95761865 0.96152498 0.90407302
 0.90737386 0.79357221 0.7677626  0.75093077 0.80245525 0.76133329
 0.59240255 0.64209404 0.63496856 0.57084243 0.60483591 0.47656044
 0.4925571  0.52240339 0.52907835 0.61720127 0.45722343 0.48189128
 0.46985549]
[0.39383057 0.45177479 0.56448583 0.41207268 0.52834966 0.34482937
 0.43211068 0.50218156 0.36640086 0.37806735 0.328287   0.19735345
 0.08429748 0.         0.05901903 0.13178766 0.17640505 0.25018613
 0.26913527 0.26801143 0.1921701  0.23910388 0.13751718 0.07946167
 0.12068289 0.10753554 0.13985546 0.20748339 0.20589517 0.24673718
 0.39781286 0.48137688 0.54566061 0.56199219 0.65107679 0.68801964
 0.63770393 0.55559983 0.58225637 0.59952179 0.38753657 0.32273176
 0.2489711  0.27255059 0.34714844 0.32506835 0.36931686 0.226995
 0.29102292 0.33242378 0.33290622 0.3834735  0.41842504 0.42377963
 0.51706432 0.53988755 0.58267981 0.63574049 0.5918247  0.62124196
 0.64548979 0.67219289 0.64303624 0.65845935 0.75224743 0.84214542
 0.88798688 0.87368286 0.93817747 0.91084291 0.79948993 0.86177535
 0.83404679 1.         0.89975632 0.89841149 0.80092098 0.73641366
 0.70951503 0.81155409 0.87267079 0.80289218 0.7477582  0.77136914
 0.67084832 0.69123495 0.71503943 0.62051549]

#### Wizualizacja asymetrii GC i kumulatywnej asymetrii GC

W celu wizualizacji dołączymy kolumnę *skew_cuml* do ramki *skewdf*

In [66]:
skew_data_final_scaled = {}

for chromname, skew_df_cuml in skew_data_cuml_scaled.items():
    skewdf = skew_df_cuml[0]
    skew_cuml_scaled = skew_df_cuml[1]

    skewdf["skew_cuml"] = skew_cuml_scaled
    print(skewdf)
    skew_data_final_scaled[chromname] = skewdf

           chr    start     stop      skew              col  skew_cuml
0   ptg000007l        0    50000  0.010524   fill_color=red   0.203531
1   ptg000007l    50000   100000  0.005253   fill_color=red   0.231053
2   ptg000007l   100000   150000 -0.025394  fill_color=blue   0.097994
3   ptg000007l   150000   200000  0.024672   fill_color=red   0.227270
4   ptg000007l   200000   250000 -0.031651  fill_color=blue   0.061428
..         ...      ...      ...       ...              ...        ...
94  ptg000007l  4700000  4750000  0.011097   fill_color=red   0.618276
95  ptg000007l  4750000  4800000  0.008320   fill_color=red   0.661872
96  ptg000007l  4800000  4850000 -0.048026  fill_color=blue   0.410229
97  ptg000007l  4850000  4900000 -0.002899  fill_color=blue   0.395039
98  ptg000007l  4900000  4950000 -0.050947  fill_color=blue   0.128092

[99 rows x 6 columns]
           chr    start     stop      skew              col  skew_cuml
0   ptg000003l        0    50000 -0.025365  fill_color=blue   0.363631
1   ptg000003l    50000   100000 -0.026361  fill_color=blue   0.172085
2   ptg000003l   100000   150000  0.002450   fill_color=red   0.189885
3   ptg000003l   150000   200000  0.002481   fill_color=red   0.207912
4   ptg000003l   200000   250000 -0.008522  fill_color=blue   0.145988
5   ptg000003l   250000   300000 -0.015273  fill_color=blue   0.035012
6   ptg000003l   300000   350000  0.006802   fill_color=red   0.084434
7   ptg000003l   350000   400000  0.011390   fill_color=red   0.167193
8   ptg000003l   400000   450000 -0.005097  fill_color=blue   0.130158
9   ptg000003l   450000   500000  0.011793   fill_color=red   0.215846
10  ptg000003l   500000   550000 -0.020304  fill_color=blue   0.068316
11  ptg000003l   550000   600000  0.005741   fill_color=red   0.110030
12  ptg000003l   600000   650000  0.010304   fill_color=red   0.184903
13  ptg000003l   650000   700000  0.006822   fill_color=red   0.234473
14  ptg000003l   700000   750000 -0.008808  fill_color=blue   0.170473
15  ptg000003l   750000   800000  0.025556   fill_color=red   0.356168
16  ptg000003l   800000   850000 -0.011348  fill_color=blue   0.273711
17  ptg000003l   850000   900000 -0.037669  fill_color=blue   0.000000
18  ptg000003l   900000   950000  0.005389   fill_color=red   0.039156
19  ptg000003l   950000  1000000  0.025880   fill_color=red   0.227204
20  ptg000003l  1000000  1050000 -0.029950  fill_color=blue   0.009579
21  ptg000003l  1050000  1100000  0.012791   fill_color=red   0.102523
22  ptg000003l  1100000  1150000  0.017551   fill_color=red   0.230053
23  ptg000003l  1150000  1200000  0.006667   fill_color=red   0.278499
24  ptg000003l  1200000  1250000  0.009122   fill_color=red   0.344781
25  ptg000003l  1250000  1300000 -0.007445  fill_color=blue   0.290687
26  ptg000003l  1300000  1350000 -0.016435  fill_color=blue   0.171269
27  ptg000003l  1350000  1400000  0.012024   fill_color=red   0.258638
28  ptg000003l  1400000  1450000  0.006942   fill_color=red   0.309081
29  ptg000003l  1450000  1500000 -0.001392  fill_color=blue   0.298965
30  ptg000003l  1500000  1550000 -0.002412  fill_color=blue   0.281441
31  ptg000003l  1550000  1600000 -0.015237  fill_color=blue   0.170726
32  ptg000003l  1600000  1650000  0.045286   fill_color=red   0.499781
33  ptg000003l  1650000  1700000  0.029414   fill_color=red   0.713511
34  ptg000003l  1700000  1750000  0.033622   fill_color=red   0.957813
35  ptg000003l  1750000  1800000  0.005806   fill_color=red   1.000000
           chr    start     stop      skew              col  skew_cuml
0   ptg000012l        0    50000 -0.015225  fill_color=blue   0.898184
1   ptg000012l    50000   100000 -0.011048  fill_color=blue   0.846921
2   ptg000012l   100000   150000  0.001069   fill_color=red   0.851880
3   ptg000012l   150000   200000 -0.026223  fill_color=blue   0.730206
4   ptg000012l   200000   250000  0.000081   fill_color=red   0.730582
5   ptg000012l   250000   300000  0.022911   fill_color=red   0.836888
6   ptg000012l   300000   350000  0.005348   fill_color=red   0.861703
7   ptg000012l   350000   400000 -0.019378  fill_color=blue   0.771791
8   ptg000012l   400000   450000  0.009520   fill_color=red   0.815963
9   ptg000012l   450000   500000  0.005338   fill_color=red   0.840731
10  ptg000012l   500000   550000  0.034326   fill_color=red   1.000000
11  ptg000012l   550000   600000 -0.016203  fill_color=blue   0.924820
12  ptg000012l   600000   650000 -0.007053  fill_color=blue   0.892093
13  ptg000012l   650000   700000 -0.003026  fill_color=blue   0.878052
14  ptg000012l   700000   750000  0.012443   fill_color=red   0.935785
15  ptg000012l   750000   800000  0.004911   fill_color=red   0.958571
16  ptg000012l   800000   850000  0.006967   fill_color=red   0.990897
17  ptg000012l   850000   900000 -0.032151  fill_color=blue   0.841718
18  ptg000012l   900000   950000 -0.057498  fill_color=blue   0.574934
19  ptg000012l   950000  1000000 -0.005946  fill_color=blue   0.547346
20  ptg000012l  1000000  1050000  0.018977   fill_color=red   0.635397
21  ptg000012l  1050000  1100000  0.002727   fill_color=red   0.648049
22  ptg000012l  1100000  1150000  0.034667   fill_color=red   0.808900
23  ptg000012l  1150000  1200000 -0.063350  fill_color=blue   0.514963
24  ptg000012l  1200000  1250000  0.011413   fill_color=red   0.567918
25  ptg000012l  1250000  1300000  0.010720   fill_color=red   0.617659
26  ptg000012l  1300000  1350000 -0.007483  fill_color=blue   0.582937
27  ptg000012l  1350000  1400000 -0.018737  fill_color=blue   0.496000
28  ptg000012l  1400000  1450000  0.002758   fill_color=red   0.508797
29  ptg000012l  1450000  1500000  0.001042   fill_color=red   0.513634
30  ptg000012l  1500000  1550000 -0.014292  fill_color=blue   0.447322
31  ptg000012l  1550000  1600000 -0.004246  fill_color=blue   0.427621
32  ptg000012l  1600000  1650000 -0.031951  fill_color=blue   0.279373
33  ptg000012l  1650000  1700000  0.005060   fill_color=red   0.302852
34  ptg000012l  1700000  1750000 -0.003266  fill_color=blue   0.287700
35  ptg000012l  1750000  1800000  0.008376   fill_color=red   0.326566
36  ptg000012l  1800000  1850000  0.016544   fill_color=red   0.403330
37  ptg000012l  1850000  1900000 -0.036056  fill_color=blue   0.236035
38  ptg000012l  1900000  1950000 -0.030288  fill_color=blue   0.095500
39  ptg000012l  1950000  2000000 -0.020582  fill_color=blue   0.000000
           chr    start     stop      skew              col  skew_cuml
0   ptg000008l        0    50000 -0.010783  fill_color=blue   0.284911
1   ptg000008l    50000   100000 -0.019570  fill_color=blue   0.114658
2   ptg000008l   100000   150000  0.006577   fill_color=red   0.171874
3   ptg000008l   150000   200000  0.001204   fill_color=red   0.182350
4   ptg000008l   200000   250000  0.005728   fill_color=red   0.232183
5   ptg000008l   250000   300000 -0.026688  fill_color=blue   0.000000
6   ptg000008l   300000   350000  0.002609   fill_color=red   0.022699
7   ptg000008l   350000   400000  0.016680   fill_color=red   0.167811
8   ptg000008l   400000   450000  0.006288   fill_color=red   0.222518
9   ptg000008l   450000   500000  0.013814   fill_color=red   0.342703
10  ptg000008l   500000   550000  0.003323   fill_color=red   0.371608
11  ptg000008l   550000   600000  0.008864   fill_color=red   0.448725
12  ptg000008l   600000   650000  0.011978   fill_color=red   0.552937
13  ptg000008l   650000   700000 -0.010009  fill_color=blue   0.465859
14  ptg000008l   700000   750000  0.021261   fill_color=red   0.650828
15  ptg000008l   750000   800000  0.014008   fill_color=red   0.772699
16  ptg000008l   800000   850000 -0.001107  fill_color=blue   0.763067
17  ptg000008l   850000   900000  0.008788   fill_color=red   0.839524
18  ptg000008l   900000   950000 -0.019193  fill_color=blue   0.672549
19  ptg000008l   950000  1000000  0.008188   fill_color=red   0.743781
20  ptg000008l  1000000  1050000  0.003788   fill_color=red   0.776738
21  ptg000008l  1050000  1100000 -0.017297  fill_color=blue   0.626252
22  ptg000008l  1100000  1150000 -0.014756  fill_color=blue   0.497876
23  ptg000008l  1150000  1200000  0.001278   fill_color=red   0.508995
24  ptg000008l  1200000  1250000  0.002847   fill_color=red   0.533763
25  ptg000008l  1250000  1300000  0.022380   fill_color=red   0.728468
26  ptg000008l  1300000  1350000  0.011666   fill_color=red   0.829960
27  ptg000008l  1350000  1400000  0.009771   fill_color=red   0.914968
28  ptg000008l  1400000  1450000 -0.003720  fill_color=blue   0.882608
29  ptg000008l  1450000  1500000  0.001134   fill_color=red   0.892471
30  ptg000008l  1500000  1550000  0.004041   fill_color=red   0.927624
31  ptg000008l  1550000  1600000 -0.017246  fill_color=blue   0.777589
32  ptg000008l  1600000  1650000 -0.001986  fill_color=blue   0.760309
33  ptg000008l  1650000  1700000  0.011632   fill_color=red   0.861509
34  ptg000008l  1700000  1750000  0.015919   fill_color=red   1.000000
35  ptg000008l  1750000  1800000 -0.015526  fill_color=blue   0.864923
36  ptg000008l  1800000  1850000 -0.017923  fill_color=blue   0.708998
37  ptg000008l  1850000  1900000 -0.004857  fill_color=blue   0.666743
38  ptg000008l  1900000  1950000 -0.019357  fill_color=blue   0.498335
39  ptg000008l  1950000  2000000  0.005762   fill_color=red   0.548461
40  ptg000008l  2000000  2050000  0.017695   fill_color=red   0.702405
41  ptg000008l  2050000  2100000 -0.008897  fill_color=blue   0.625003
42  ptg000008l  2100000  2150000  0.008505   fill_color=red   0.698998
43  ptg000008l  2150000  2200000  0.023927   fill_color=red   0.907157
44  ptg000008l  2200000  2250000 -0.025389  fill_color=blue   0.686275
45  ptg000008l  2250000  2300000 -0.001997  fill_color=blue   0.668902
           chr    start     stop      skew              col  skew_cuml
0   ptg000002l        0    50000 -0.005010  fill_color=blue   0.406626
1   ptg000002l    50000   100000 -0.027096  fill_color=blue   0.249364
2   ptg000002l   100000   150000 -0.019400  fill_color=blue   0.136768
3   ptg000002l   150000   200000  0.012143   fill_color=red   0.207247
4   ptg000002l   200000   250000 -0.003573  fill_color=blue   0.186512
5   ptg000002l   250000   300000  0.025505   fill_color=red   0.334540
6   ptg000002l   300000   350000 -0.019065  fill_color=blue   0.223889
7   ptg000002l   350000   400000  0.001208   fill_color=red   0.230900
8   ptg000002l   400000   450000  0.003219   fill_color=red   0.249581
9   ptg000002l   450000   500000  0.019490   fill_color=red   0.362701
10  ptg000002l   500000   550000 -0.022781  fill_color=blue   0.230481
11  ptg000002l   550000   600000 -0.001955  fill_color=blue   0.219133
12  ptg000002l   600000   650000  0.023334   fill_color=red   0.354560
13  ptg000002l   650000   700000  0.016329   fill_color=red   0.449334
14  ptg000002l   700000   750000 -0.000331  fill_color=blue   0.447415
15  ptg000002l   750000   800000  0.015781   fill_color=red   0.539005
16  ptg000002l   800000   850000  0.032182   fill_color=red   0.725787
17  ptg000002l   850000   900000  0.047246   fill_color=red   1.000000
18  ptg000002l   900000   950000 -0.104098  fill_color=blue   0.395822
19  ptg000002l   950000  1000000 -0.032858  fill_color=blue   0.205114
20  ptg000002l  1000000  1050000 -0.006640  fill_color=blue   0.166575
21  ptg000002l  1050000  1100000  0.010480   fill_color=red   0.227398
22  ptg000002l  1100000  1150000  0.000598   fill_color=red   0.230869
23  ptg000002l  1150000  1200000  0.013489   fill_color=red   0.309157
24  ptg000002l  1200000  1250000 -0.007521  fill_color=blue   0.265508
25  ptg000002l  1250000  1300000  0.001165   fill_color=red   0.272272
26  ptg000002l  1300000  1350000 -0.015183  fill_color=blue   0.184149
27  ptg000002l  1350000  1400000  0.016240   fill_color=red   0.278407
28  ptg000002l  1400000  1450000  0.014552   fill_color=red   0.362866
29  ptg000002l  1450000  1500000 -0.021027  fill_color=blue   0.240829
30  ptg000002l  1500000  1550000 -0.010501  fill_color=blue   0.179884
31  ptg000002l  1550000  1600000  0.002917   fill_color=red   0.196816
32  ptg000002l  1600000  1650000 -0.016435  fill_color=blue   0.101427
33  ptg000002l  1650000  1700000 -0.005844  fill_color=blue   0.067509
34  ptg000002l  1700000  1750000  0.020416   fill_color=red   0.186005
35  ptg000002l  1750000  1800000 -0.016850  fill_color=blue   0.088211
36  ptg000002l  1800000  1850000  0.001023   fill_color=red   0.094147
37  ptg000002l  1850000  1900000 -0.016221  fill_color=blue   0.000000
38  ptg000002l  1900000  1950000  0.015131   fill_color=red   0.087820
39  ptg000002l  1950000  2000000  0.016841   fill_color=red   0.185565
40  ptg000002l  2000000  2050000  0.001476   fill_color=red   0.194132
41  ptg000002l  2050000  2100000  0.025269   fill_color=red   0.340793
42  ptg000002l  2100000  2150000  0.000162   fill_color=red   0.341736
43  ptg000002l  2150000  2200000 -0.013777  fill_color=blue   0.261774
44  ptg000002l  2200000  2250000  0.027147   fill_color=red   0.419331
           chr    start     stop      skew              col  skew_cuml
0   ptg000016l        0    50000 -0.020821  fill_color=blue   0.901081
1   ptg000016l    50000   100000 -0.019590  fill_color=blue   0.744831
2   ptg000016l   100000   150000  0.031991   fill_color=red   1.000000
3   ptg000016l   150000   200000 -0.008140  fill_color=blue   0.935074
4   ptg000016l   200000   250000 -0.000288  fill_color=blue   0.932775
5   ptg000016l   250000   300000 -0.008699  fill_color=blue   0.863390
6   ptg000016l   300000   350000 -0.009415  fill_color=blue   0.788295
7   ptg000016l   350000   400000 -0.007018  fill_color=blue   0.732319
8   ptg000016l   400000   450000  0.030090   fill_color=red   0.972320
9   ptg000016l   450000   500000 -0.025572  fill_color=blue   0.768354
10  ptg000016l   500000   550000  0.018525   fill_color=red   0.916114
11  ptg000016l   550000   600000  0.004666   fill_color=red   0.953331
12  ptg000016l   600000   650000 -0.012703  fill_color=blue   0.852006
13  ptg000016l   650000   700000  0.000529   fill_color=red   0.856228
14  ptg000016l   700000   750000 -0.027023  fill_color=blue   0.640691
15  ptg000016l   750000   800000 -0.018115  fill_color=blue   0.496200
16  ptg000016l   800000   850000  0.007845   fill_color=red   0.558769
17  ptg000016l   850000   900000 -0.003761  fill_color=blue   0.528768
18  ptg000016l   900000   950000  0.007273   fill_color=red   0.586782
19  ptg000016l   950000  1000000 -0.008428  fill_color=blue   0.519560
20  ptg000016l  1000000  1050000 -0.003205  fill_color=blue   0.494000
21  ptg000016l  1050000  1100000 -0.009661  fill_color=blue   0.416940
22  ptg000016l  1100000  1150000 -0.008132  fill_color=blue   0.352077
23  ptg000016l  1150000  1200000  0.008782   fill_color=red   0.422123
24  ptg000016l  1200000  1250000 -0.021897  fill_color=blue   0.247472
25  ptg000016l  1250000  1300000 -0.016447  fill_color=blue   0.116291
26  ptg000016l  1300000  1350000 -0.014580  fill_color=blue   0.000000
27  ptg000016l  1350000  1400000  0.009526   fill_color=red   0.075982
28  ptg000016l  1400000  1450000 -0.008631  fill_color=blue   0.007142
29  ptg000016l  1450000  1500000  0.001752   fill_color=red   0.021119
30  ptg000016l  1500000  1550000 -0.002456  fill_color=blue   0.001526
31  ptg000016l  1550000  1600000  0.002599   fill_color=red   0.022255
32  ptg000016l  1600000  1650000  0.014834   fill_color=red   0.140571
33  ptg000016l  1650000  1700000  0.043929   fill_color=red   0.490954
34  ptg000016l  1700000  1750000 -0.001427  fill_color=blue   0.479574
35  ptg000016l  1750000  1800000  0.006938   fill_color=red   0.534910
36  ptg000016l  1800000  1850000 -0.010494  fill_color=blue   0.451210
37  ptg000016l  1850000  1900000 -0.012539  fill_color=blue   0.351195
38  ptg000016l  1900000  1950000 -0.010925  fill_color=blue   0.264058
39  ptg000016l  1950000  2000000 -0.005623  fill_color=blue   0.219205
40  ptg000016l  2000000  2050000 -0.011545  fill_color=blue   0.127122
41  ptg000016l  2050000  2100000  0.009041   fill_color=red   0.199231
42  ptg000016l  2100000  2150000  0.007090   fill_color=red   0.255785
43  ptg000016l  2150000  2200000  0.018418   fill_color=red   0.402687
44  ptg000016l  2200000  2250000  0.005460   fill_color=red   0.446240
45  ptg000016l  2250000  2300000  0.021988   fill_color=red   0.621623
           chr    start     stop      skew              col  skew_cuml
0   ptg000018l        0    50000  0.020662   fill_color=red   0.980084
1   ptg000018l    50000   100000 -0.061138  fill_color=blue   0.680197
2   ptg000018l   100000   150000  0.006225   fill_color=red   0.710731
3   ptg000018l   150000   200000  0.011075   fill_color=red   0.765055
4   ptg000018l   200000   250000 -0.026115  fill_color=blue   0.636961
5   ptg000018l   250000   300000  0.005756   fill_color=red   0.665195
6   ptg000018l   300000   350000 -0.014480  fill_color=blue   0.594170
7   ptg000018l   350000   400000 -0.008692  fill_color=blue   0.551535
8   ptg000018l   400000   450000 -0.003086  fill_color=blue   0.536400
9   ptg000018l   450000   500000  0.014753   fill_color=red   0.608766
10  ptg000018l   500000   550000  0.013464   fill_color=red   0.674809
11  ptg000018l   550000   600000 -0.016295  fill_color=blue   0.594883
12  ptg000018l   600000   650000 -0.010849  fill_color=blue   0.541666
13  ptg000018l   650000   700000 -0.004286  fill_color=blue   0.520642
14  ptg000018l   700000   750000  0.010673   fill_color=red   0.572994
15  ptg000018l   750000   800000 -0.002781  fill_color=blue   0.559353
16  ptg000018l   800000   850000  0.013853   fill_color=red   0.627303
17  ptg000018l   850000   900000  0.008851   fill_color=red   0.670718
18  ptg000018l   900000   950000  0.029158   fill_color=red   0.813738
19  ptg000018l   950000  1000000  0.001954   fill_color=red   0.823325
20  ptg000018l  1000000  1050000  0.004624   fill_color=red   0.846004
21  ptg000018l  1050000  1100000 -0.009206  fill_color=blue   0.800848
22  ptg000018l  1100000  1150000  0.037181   fill_color=red   0.983224
23  ptg000018l  1150000  1200000 -0.005419  fill_color=blue   0.956643
24  ptg000018l  1200000  1250000 -0.008288  fill_color=blue   0.915990
25  ptg000018l  1250000  1300000  0.017127   fill_color=red   1.000000
26  ptg000018l  1300000  1350000 -0.010652  fill_color=blue   0.947752
27  ptg000018l  1350000  1400000 -0.027796  fill_color=blue   0.811408
28  ptg000018l  1400000  1450000 -0.031889  fill_color=blue   0.654990
29  ptg000018l  1450000  1500000 -0.010154  fill_color=blue   0.605182
30  ptg000018l  1500000  1550000  0.008410   fill_color=red   0.646435
31  ptg000018l  1550000  1600000  0.006699   fill_color=red   0.679293
32  ptg000018l  1600000  1650000 -0.006514  fill_color=blue   0.647340
33  ptg000018l  1650000  1700000 -0.022274  fill_color=blue   0.538086
34  ptg000018l  1700000  1750000  0.044041   fill_color=red   0.754112
35  ptg000018l  1750000  1800000 -0.003510  fill_color=blue   0.736895
36  ptg000018l  1800000  1850000 -0.010440  fill_color=blue   0.685687
37  ptg000018l  1850000  1900000 -0.000415  fill_color=blue   0.683651
38  ptg000018l  1900000  1950000 -0.012882  fill_color=blue   0.620462
39  ptg000018l  1950000  2000000 -0.007280  fill_color=blue   0.584754
40  ptg000018l  2000000  2050000  0.006896   fill_color=red   0.618579
41  ptg000018l  2050000  2100000 -0.022047  fill_color=blue   0.510435
42  ptg000018l  2100000  2150000 -0.000666  fill_color=blue   0.507168
43  ptg000018l  2150000  2200000  0.030504   fill_color=red   0.656795
44  ptg000018l  2200000  2250000  0.009823   fill_color=red   0.704978
45  ptg000018l  2250000  2300000  0.032551   fill_color=red   0.864643
46  ptg000018l  2300000  2350000 -0.019986  fill_color=blue   0.766611
47  ptg000018l  2350000  2400000  0.000613   fill_color=red   0.769617
48  ptg000018l  2400000  2450000 -0.030618  fill_color=blue   0.619433
49  ptg000018l  2450000  2500000 -0.126284  fill_color=blue   0.000000

#### Zmiana formatu z szerokiego (wide) na długi (long)

In [67]:
skew_data_final_molten = {}

for chromname, skewdf in skew_data_final_scaled.items():
    skewdf_molten = pd.melt(skewdf, id_vars=["start","stop"], value_vars=["skew","skew_cuml"])
    
    skew_data_final_molten[chromname] = skewdf_molten
    print(skewdf_molten)

       start     stop   variable     value
0          0    50000       skew  0.010524
1      50000   100000       skew  0.005253
2     100000   150000       skew -0.025394
3     150000   200000       skew  0.024672
4     200000   250000       skew -0.031651
..       ...      ...        ...       ...
193  4700000  4750000  skew_cuml  0.618276
194  4750000  4800000  skew_cuml  0.661872
195  4800000  4850000  skew_cuml  0.410229
196  4850000  4900000  skew_cuml  0.395039
197  4900000  4950000  skew_cuml  0.128092

[198 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew -0.025365
1     50000   100000       skew -0.026361
2    100000   150000       skew  0.002450
3    150000   200000       skew  0.002481
4    200000   250000       skew -0.008522
..      ...      ...        ...       ...
67  1550000  1600000  skew_cuml  0.170726
68  1600000  1650000  skew_cuml  0.499781
69  1650000  1700000  skew_cuml  0.713511
70  1700000  1750000  skew_cuml  0.957813
71  1750000  1800000  skew_cuml  1.000000

[72 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew -0.015225
1     50000   100000       skew -0.011048
2    100000   150000       skew  0.001069
3    150000   200000       skew -0.026223
4    200000   250000       skew  0.000081
..      ...      ...        ...       ...
75  1750000  1800000  skew_cuml  0.326566
76  1800000  1850000  skew_cuml  0.403330
77  1850000  1900000  skew_cuml  0.236035
78  1900000  1950000  skew_cuml  0.095500
79  1950000  2000000  skew_cuml  0.000000

[80 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew -0.010783
1     50000   100000       skew -0.019570
2    100000   150000       skew  0.006577
3    150000   200000       skew  0.001204
4    200000   250000       skew  0.005728
..      ...      ...        ...       ...
87  2050000  2100000  skew_cuml  0.625003
88  2100000  2150000  skew_cuml  0.698998
89  2150000  2200000  skew_cuml  0.907157
90  2200000  2250000  skew_cuml  0.686275
91  2250000  2300000  skew_cuml  0.668902

[92 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew -0.005010
1     50000   100000       skew -0.027096
2    100000   150000       skew -0.019400
3    150000   200000       skew  0.012143
4    200000   250000       skew -0.003573
..      ...      ...        ...       ...
85  2000000  2050000  skew_cuml  0.194132
86  2050000  2100000  skew_cuml  0.340793
87  2100000  2150000  skew_cuml  0.341736
88  2150000  2200000  skew_cuml  0.261774
89  2200000  2250000  skew_cuml  0.419331

[90 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew -0.020821
1     50000   100000       skew -0.019590
2    100000   150000       skew  0.031991
3    150000   200000       skew -0.008140
4    200000   250000       skew -0.000288
..      ...      ...        ...       ...
87  2050000  2100000  skew_cuml  0.199231
88  2100000  2150000  skew_cuml  0.255785
89  2150000  2200000  skew_cuml  0.402687
90  2200000  2250000  skew_cuml  0.446240
91  2250000  2300000  skew_cuml  0.621623

[92 rows x 4 columns]
      start     stop   variable     value
0         0    50000       skew  0.020662
1     50000   100000       skew -0.061138
2    100000   150000       skew  0.006225
3    150000   200000       skew  0.011075
4    200000   250000       skew -0.026115
..      ...      ...        ...       ...
95  2250000  2300000  skew_cuml  0.864643
96  2300000  2350000  skew_cuml  0.766611
97  2350000  2400000  skew_cuml  0.769617
98  2400000  2450000  skew_cuml  0.619433
99  2450000  2500000  skew_cuml  0.000000

[100 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.035127
1      50000   100000       skew -0.080898
2     100000   150000       skew  0.002225
3     150000   200000       skew  0.001202
4     200000   250000       skew -0.031109
..       ...      ...        ...       ...
107  2550000  2600000  skew_cuml  0.798098
108  2600000  2650000  skew_cuml  0.823979
109  2650000  2700000  skew_cuml  0.541120
110  2700000  2750000  skew_cuml  0.415404
111  2750000  2800000  skew_cuml  0.651949

[112 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.006391
1      50000   100000       skew  0.015092
2     100000   150000       skew  0.006172
3     150000   200000       skew  0.012518
4     200000   250000       skew  0.031908
..       ...      ...        ...       ...
119  2850000  2900000  skew_cuml  0.882115
120  2900000  2950000  skew_cuml  0.912533
121  2950000  3000000  skew_cuml  0.846564
122  3000000  3050000  skew_cuml  0.868300
123  3050000  3100000  skew_cuml  1.000000

[124 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.016420
1      50000   100000       skew -0.005388
2     100000   150000       skew  0.015633
3     150000   200000       skew  0.005352
4     200000   250000       skew -0.022909
..       ...      ...        ...       ...
127  3050000  3100000  skew_cuml  0.894282
128  3100000  3150000  skew_cuml  0.928218
129  3150000  3200000  skew_cuml  0.894169
130  3200000  3250000  skew_cuml  0.816803
131  3250000  3300000  skew_cuml  0.730713

[132 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.049457
1      50000   100000       skew -0.010999
2     100000   150000       skew -0.063589
3     150000   200000       skew  0.008714
4     200000   250000       skew  0.036506
..       ...      ...        ...       ...
159  3850000  3900000  skew_cuml  0.635131
160  3900000  3950000  skew_cuml  0.693029
161  3950000  4000000  skew_cuml  0.863827
162  4000000  4050000  skew_cuml  0.909134
163  4050000  4100000  skew_cuml  1.000000

[164 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.005539
1      50000   100000       skew -0.017074
2     100000   150000       skew  0.007227
3     150000   200000       skew -0.014320
4     200000   250000       skew -0.036160
..       ...      ...        ...       ...
143  3450000  3500000  skew_cuml  0.800800
144  3500000  3550000  skew_cuml  0.778732
145  3550000  3600000  skew_cuml  0.737300
146  3600000  3650000  skew_cuml  0.725941
147  3650000  3700000  skew_cuml  0.746615

[148 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.000000
1      50000   100000       skew -0.010456
2     100000   150000       skew -0.002581
3     150000   200000       skew -0.003627
4     200000   250000       skew  0.033700
..       ...      ...        ...       ...
143  3450000  3500000  skew_cuml  0.829189
144  3500000  3550000  skew_cuml  0.875206
145  3550000  3600000  skew_cuml  0.943900
146  3600000  3650000  skew_cuml  0.983843
147  3650000  3700000  skew_cuml  0.999750

[148 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.000775
1      50000   100000       skew  0.005545
2     100000   150000       skew  0.005701
3     150000   200000       skew  0.006454
4     200000   250000       skew -0.015326
..       ...      ...        ...       ...
163  3950000  4000000  skew_cuml  0.387332
164  4000000  4050000  skew_cuml  0.351857
165  4050000  4100000  skew_cuml  0.265597
166  4100000  4150000  skew_cuml  0.391475
167  4150000  4200000  skew_cuml  0.629696

[168 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew -0.011170
1      50000   100000       skew -0.012523
2     100000   150000       skew  0.008134
3     150000   200000       skew  0.017235
4     200000   250000       skew -0.011566
..       ...      ...        ...       ...
165  4000000  4050000  skew_cuml  0.529078
166  4050000  4100000  skew_cuml  0.617201
167  4100000  4150000  skew_cuml  0.457223
168  4150000  4200000  skew_cuml  0.481891
169  4200000  4250000  skew_cuml  0.469855

[170 rows x 4 columns]
       start     stop   variable     value
0          0    50000       skew  0.094333
1      50000   100000       skew  0.014707
2     100000   150000       skew  0.028607
3     150000   200000       skew -0.038683
4     200000   250000       skew  0.029512
..       ...      ...        ...       ...
171  4150000  4200000  skew_cuml  0.771369
172  4200000  4250000  skew_cuml  0.670848
173  4250000  4300000  skew_cuml  0.691235
174  4300000  4350000  skew_cuml  0.715039
175  4350000  4400000  skew_cuml  0.620515

[176 rows x 4 columns]

#### Wizualizacja

Dla wielu bakteryjnych genomów bakteryjnych wykres asymetrii GC przyjmuje charakterystyczny kształt, z punktami przełamania odpowiadającym miejscom inicjacji i terminacji replikacji (ori). Jest to bardzo interesujący przykład analizy prostych parametrów sekwencji mającej bezpośrednie przełożenie na biologię. 

Dla zainteresowanych tematem:
- [Analyzing genomes with cumulative skew diagrams](https://academic.oup.com/nar/article/26/10/2286/1030593)
- [Asymmetric substitution patterns: a review of possible underlying mutational or selective mechanisms](https://www.sciencedirect.com/science/article/pii/S0378111999002978?via%3Dihub)
- [SkewIT: The Skew Index Test for large-scale GC Skew analysis of bacterial genomes](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7717575)

In [74]:
for chromname, skewdf_molten in skew_data_final_molten.items():
    skewplot = (ggplot(skewdf_molten, aes(x="start", y="value", color="variable")) + geom_line() +
           theme_minimal() + ylab("") + xlab("Position [bp]") + scale_colour_discrete(labels=["GC skew", "Cumulative GC skew" ]) +
           labs(colour=""))
    skewplot.save(f"skew_plot_molten_{chromname}.png", width=8, height=6)

/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000007l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000003l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000012l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000008l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000002l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000016l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000018l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000014l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000011l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000015l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000010l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000004l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000001l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000009l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000013l.png
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 8 x 6 in image.
/opt/miniconda3/envs/jupyternotebook/lib/python3.11/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: skew_plot_molten_ptg000017l.png

### Sformatowanie danych do narzędzia Circos

Dane dotyczące kumulatywnej zawartości GC zwizualizujemy w postaci wykresu liniowego. Format danych dla tego typu wykresu, tak jak w poprzednim przypadku nie ulega zmianie.

In [37]:
for chromname, skewdf_molten in skew_data_final_molten.items():
    print(skewdf_molten)

             chr   start    stop      skew              col  skew_cuml
0    NC_000908.2       0    5000  0.104668   fill_color=red   0.000000
1    NC_000908.2    5000   10000  0.113294   fill_color=red   0.043697
2    NC_000908.2   10000   15000  0.018018   fill_color=red   0.050646
3    NC_000908.2   15000   20000  0.078929   fill_color=red   0.081089
4    NC_000908.2   20000   25000  0.119241   fill_color=red   0.127080
..           ...     ...     ...       ...              ...        ...
111  NC_000908.2  555000  560000  0.026263   fill_color=red   0.148306
112  NC_000908.2  560000  565000 -0.059786  fill_color=blue   0.125247
113  NC_000908.2  565000  570000 -0.045847  fill_color=blue   0.107564
114  NC_000908.2  570000  575000 -0.022279  fill_color=blue   0.098971
115  NC_000908.2  575000  580000 -0.040559  fill_color=blue   0.083328

[116 rows x 6 columns]

In [76]:
c_skew_data_final_molten = {}

for chromname, skewdf_molten in skew_data_final_molten.items():
    print(skewdf_molten.columns)
    c_skewdf = skewdf_molten[["chr","start","stop","skew_cuml"]].copy()
    c_skewdf['col'] = "color=pink"
    c_skew_data_final_molten[chromname] = c_skewdf

    print(c_skewdf)

Index(['start', 'stop', 'variable', 'value'], dtype='object')

KeyError: "['chr', 'skew_cuml'] not in index"

In [71]:
for chromname, c_skewdf in c_skew_data_final_molten.items():
    print(chromname)
    c_skewdf.to_csv(f"gc_skew_cumul_{chromname}.histo", sep="\t", index=False, header=False)

ptg000007l
ptg000003l
ptg000012l
ptg000008l
ptg000002l
ptg000016l
ptg000018l
ptg000014l
ptg000011l
ptg000015l
ptg000010l
ptg000004l
ptg000001l
ptg000009l
ptg000013l
ptg000017l

## Wizualizacja połączeń oraz kafelków na wykresie typu Circos

Aby zapoznać się z elementami typu "links" (połączenia) oraz "tile" (kafelek) na wykresie Circos wykorzystamy pozycje najliczniej wystepującego 20-meru. W tym celu najpierw zliczymy wystąpienia obecnych w sekwencji 20-merów.

In [40]:
kmers = kmer_freq(seq)
kmers = sorted(kmers.items(), key=lambda n: n[1], reverse=True)
kmers[0]

('TAGTAGTAGTAGTAGTAGTA', 29)

### Znajdowanie Pozycji 20-mera o Największej Częstości

W tej sekcji zidentyfikujemy 20-mer o największej częstości w sekwencji genomu i znajdziemy jego pozycje na genomie.

In [41]:
max_kmer = kmers[0][0]
kpos = kmer_pos(seq, max_kmer)
kpos

[(169475, 169495),
 (169478, 169498),
 (169481, 169501),
 (169484, 169504),
 (169487, 169507),
 (169490, 169510),
 (169493, 169513),
 (169496, 169516),
 (169499, 169519),
 (169502, 169522),
 (224532, 224552),
 (224535, 224555),
 (227128, 227148),
 (227131, 227151),
 (227134, 227154),
 (227137, 227157),
 (227140, 227160),
 (227143, 227163),
 (227146, 227166),
 (351452, 351472),
 (351455, 351475),
 (351458, 351478),
 (351461, 351481),
 (351464, 351484),
 (429304, 429324),
 (429307, 429327),
 (429310, 429330),
 (429313, 429333),
 (429316, 429336)]

#### Połączenie nakładających się zakresów

In [42]:
kpos_merged = merge_overlaps(kpos)
kpos_merged

[[169475, 169522],
 [224532, 224555],
 [227128, 227166],
 [351452, 351484],
 [429304, 429336]]

#### Przygotowanie Danych do Circos

Teraz, gdy mamy pozycje 20-merów, które chcemy wyświetlić w Circos, przygotujemy dane, które będą zgodne z tym narzędziem do wizualizacji.
Pozycje 20-merów, które uwidocznimy w postaci kafelków sformatujemy w sposób tożsamy z poprzednimi danymi.

In [43]:
with open("max_kmer.histo", "w") as out:
    col = "darkblue"
    for line in kpos_merged:
        lineout = [chromname] + line + [f"color={col}"]
        print(lineout)
        out.write("\t".join([str(x) for x in lineout]) + "\n")

['NC_000908.2', 169475, 169522, 'color=darkblue']
['NC_000908.2', 224532, 224555, 'color=darkblue']
['NC_000908.2', 227128, 227166, 'color=darkblue']
['NC_000908.2', 351452, 351484, 'color=darkblue']
['NC_000908.2', 429304, 429336, 'color=darkblue']

### Wizualizacja połączeń (links)

Połączenia w obrębie wykresów Circos wykorzystywane są m.in. do wizualizacji regionów homologicznych. Tutaj jako przykład wykorzystamy znane nam pozycje najliczniejszego 20-meru.

Połączenia definiujemy określając łączone pary zakresów w pojedynczych liniach:

|chrom1|start1|stop1|chrom2|start2|stop2|parametry
|--|--|--|--|--|--|--|
|	0|	169475|	169522	|	0|	224535	|224555	|color=blue
|	0|	33243	|35664	|	1|	442	|816	|color=blue

In [44]:
# Create an empty DataFrame to store the results
kmer_links_df = pd.DataFrame(columns=["Chromname1", "Start1", "Stop1","Chromname2", "Start2", "Stop2","Color"])
col = "blue"

for i in range(len(kpos_merged)):
    for j in range(i,len(kpos_merged)):
        if i != j:
            lineout = [chromname, *kpos_merged[i], chromname, *kpos_merged[j], f"color={col}"]
            kmer_links_df.loc[len(kmer_links_df)] = lineout

kmer_links_df

    Chromname1  Start1   Stop1   Chromname2  Start2   Stop2       Color
0  NC_000908.2  169475  169522  NC_000908.2  224532  224555  color=blue
1  NC_000908.2  169475  169522  NC_000908.2  227128  227166  color=blue
2  NC_000908.2  169475  169522  NC_000908.2  351452  351484  color=blue
3  NC_000908.2  169475  169522  NC_000908.2  429304  429336  color=blue
4  NC_000908.2  224532  224555  NC_000908.2  227128  227166  color=blue
5  NC_000908.2  224532  224555  NC_000908.2  351452  351484  color=blue
6  NC_000908.2  224532  224555  NC_000908.2  429304  429336  color=blue
7  NC_000908.2  227128  227166  NC_000908.2  351452  351484  color=blue
8  NC_000908.2  227128  227166  NC_000908.2  429304  429336  color=blue
9  NC_000908.2  351452  351484  NC_000908.2  429304  429336  color=blue

In [45]:
# Write the DataFrame to a file
kmer_links_df.to_csv("max_kmer.links", sep="\t", index=False, header=False)

### Pliki konfiguracyjne Circos

Aby stworzyć wykres, oprócz danych, musimy przygotować kilka plików konfiguracyjnych, w których definiujemy sposób w jaki wyświetlone mają być nasze dane.

Są to:

#### Kariotyp

Określamy w nim podstawowe informacje dotyczące segmentów (chromosomów), które chcemy zwizualizować. Format:

|chr|- |ID (w danych)|etykieta|początek|koniec|kolor 
|--|--|--|--|--|--|--|
|chr|	-|	1|	chromosome1|	0|	580076|	purple|

W tym przykładzie kariotyp jest mało skomplikowany, i możemy go w prosty sposób wygenerować korzystając z dostepnych danych.

In [46]:
karyo = ["chr","-",chromname,"chromosome","0",str(seq_length),"purple"]
karyo

['chr', '-', 'NC_000908.2', 'chromosome', '0', '580076', 'purple']

In [47]:
with open("karyo.conf", "w") as out: out.write("\t".join(karyo)+"\n")


#### Główny plik konfiguracyjny

Definiujemy w nim elementy grafiki, oraz ich parametry. W głównym pliku konfiguracyjnym określamy lokalizację pliku z kariotypem:

>  karyotype = karyo.conf

Elementami, które możemy uwzględnić na wykresie są m.in.:

Ideogramy, czyli segmenty "chromosomów":

> \<ideogram\>
> 
> \<spacing\> default = 0.005r \</spacing\>
> 
> radius           = 0.90r 
> thickness        = 20p 
> fill             = yes
> 
> #stroke_thickness = 1
> #stroke_color     = black
> 
> 
> \</ideogram\>

Oznaczenia osi (ticks):

> \<tick> spacing        = 10000 u
>  color          = grey 
>  size           = 10p
>   \</tick>

 Wykresy prezentujące dane liczbowe:

> \<plot>
> 
> type = histogram
>  file = gc_content.histo
>   thickness = 0p
> 
> \</plot>

Linie łączące elementy wykresu:

> \<links> 
> \<link> radius = 0.8r 
> bezier_radius = 0r 
> bezier_radius_purity = 0.9
>  color = black 
>  thickness = 2 
>  file = max_kmer.links 
>  \</link> 
>  \</links>

Plik konfiguracyjny do tego ćwiczenia możemy pobrać z chmury:

In [48]:
!wget "https://drive.google.com/uc?export=download&id=1eWXYScnQnOAyd50cI3ycwpigDJFxlvSv" -O circos_conf.conf
!ls | grep conf

--2025-10-28 13:15:21--  https://drive.google.com/uc?export=download&id=1eWXYScnQnOAyd50cI3ycwpigDJFxlvSv
Resolving drive.google.com (drive.google.com)... 216.58.208.206, 2a00:1450:401b:800::200e
Connecting to drive.google.com (drive.google.com)|216.58.208.206|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1eWXYScnQnOAyd50cI3ycwpigDJFxlvSv&export=download [following]
--2025-10-28 13:15:21--  https://drive.usercontent.google.com/download?id=1eWXYScnQnOAyd50cI3ycwpigDJFxlvSv&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.38.161, 2a00:1450:401b:802::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.38.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1820 (1.8K) [application/octet-stream]
Saving to: ‘circos_conf.conf’

circos_conf.conf    100%[===================>]   1.78K  --.-KB/s    in 0s

2025-10-28 13:15:22 (55.0 MB/s) - ‘circos_conf.conf’ saved [1820/1820]

circos_conf (1).conf
circos_conf.conf
karyo.conf
ticks (1).conf
ticks.conf

In [49]:
!cat circos_conf.conf

########## Kariotyp - tutaj definiujemy chromosomy
karyotype = karyo.conf



<ideogram>

<spacing>
# spacing between ideograms
default = 0.005r
</spacing>

# ideogram position, thickness and fill
radius           = 0.90r
thickness        = 20p
fill             = yes

#stroke_thickness = 1
#stroke_color     = black


</ideogram>


####### Ta część w zasadzie jest skopiowana z pliku przykładowego:

<image>
<<include etc/image.conf>> # included from Circos distribution
radius* = 1500
</image>


# RGB/HSV color definitions, color lists, location of fonts,
# fill patterns
<<include etc/colors_fonts_patterns.conf>> # included from Circos distribution

# debugging, I/O an dother system parameters
<<include etc/housekeeping.conf>> # included from Circos distribution

#<ticks> blocks to define ticks, tick labels and grids
#
# requires that chromosomes_units be defined
#


### Znaczniki na osiach:
<<include ticks.conf>>



<plots>


#### GC-content
<plot>

type = histogram
file = gc_content.histo
thickness = 0p

</plot>

#### GC-skew
<plot>

type = scatter
file = gc_skew.histo
thickness = 0p
r1        = 0.95r
r0        = 0.85r

<axes>
<axis>
spacing = 0.1r
color = grey_a3
thickness = 1
</axis>
</axes>

</plot>

#### Cumulative GC_skew:
<plot>

type = line
file = gc_skew_cumul.histo
thickness = 2p


<axes>
<axis>
spacing = 0.1r
color = grey_a3
thickness = 1
</axis>
</axes>
</plot>

### Pozycja najliczniejszego K-meru:
<plot>
type = tile
file = max_kmer.histo
r1 = 0.98r
r0 = 0.86r


layers      = 15
margin      = 0.02u
orientation = out

thickness   = 15
padding     = 8

</plot>


</plots>

### Połączenia między pozycjami z najliczniejszym K-merem:
<links>
<link>
radius = 0.8r
bezier_radius = 0r
bezier_radius_purity = 0.9
color = black
thickness = 2
file = max_kmer.links
</link>
</links>

#### Dodatkowe pliki konfiguracyjne 

Możemy definiować w nich te same typy elementów, co w głównym pliku konfiguracyjnym. Uwzględniamy je w głównym pliku linijką \<\<include name.conf\>\>.

In [50]:
!wget "https://drive.google.com/uc?export=download&id=11ZgDy-rKfUbjYmsZOSfnFJLAwBcm-C5_" -O ticks.conf
!ls | grep conf

--2025-10-28 13:15:25--  https://drive.google.com/uc?export=download&id=11ZgDy-rKfUbjYmsZOSfnFJLAwBcm-C5_
Resolving drive.google.com (drive.google.com)... 216.58.208.206, 2a00:1450:401b:800::200e
Connecting to drive.google.com (drive.google.com)|216.58.208.206|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=11ZgDy-rKfUbjYmsZOSfnFJLAwBcm-C5_&export=download [following]
--2025-10-28 13:15:26--  https://drive.usercontent.google.com/download?id=11ZgDy-rKfUbjYmsZOSfnFJLAwBcm-C5_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.38.161, 2a00:1450:401b:802::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.38.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 499 [application/octet-stream]
Saving to: ‘ticks.conf’

ticks.conf          100%[===================>]     499  --.-KB/s    in 0s

2025-10-28 13:15:27 (18.0 MB/s) - ‘ticks.conf’ saved [499/499]

circos_conf (1).conf
circos_conf.conf
karyo.conf
ticks (1).conf
ticks.conf

In [51]:
!cat ticks.conf

show_ticks          = yes
show_tick_labels    = yes

<ticks>
skip_first_label = no
skip_last_label = no
radius           = dims(ideogram,radius_outer)
multiplier       = 1
color            = black
thickness        = 2p
size             = 20p

<tick>
skip_first_label = no
spacing        = 100000u
show_label     = yes
label_size     = 20p
label_offset   = 10p
format         = %d
suffix = " bp"
</tick>

<tick>
spacing        = 10000 u
color          = grey
size           = 10p
</tick>

</ticks>

### Wywołanie Circos

In [52]:
!circos -conf circos_conf.conf

/bin/bash: line 1: circos: command not found